/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package umsa.capricornio.gui.transacciones;

import java.rmi.RemoteException;
import java.util.Map;
import javax.xml.rpc.ServiceException;
import umsa.capricornio.gui.ConnectADQUI.AdquiWSServiceLocator;
import umsa.capricornio.gui.ConnectADQUI.AdquiWS_PortType;

/**
 *
 * @author UMSA-JES
 */
public class JD_CambiaPartida extends javax.swing.JDialog {

    /**
     * Creates new form JD_CambiaPartida
     */
    String cod_item, articulo, unidad_medida,cod_trans_detalle,partida;
    int gestion, cod_tipo_item;        
    public JD_CambiaPartida(java.awt.Frame parent, boolean modal,String cod_trans_detalle,String cod_item,int gestion) {
        super(parent, modal);
        initComponents();
        this.cod_trans_detalle = cod_trans_detalle;
        this.cod_item = cod_item;
        this.gestion = gestion;
        this.setLocationRelativeTo(null);
        this.setTitle("CAMBIAR PARTIDA");
        System.out.println("Los datos recibidos son... cod_item: "+this.cod_item+" y gestion: "+this.gestion);
        this.JTA_Descripcion.setEditable(false);
        this.getDataItems();
        LlenaComboPartidas();
    }

    public void LlenaComboPartidas(){
            try {
                AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
                AdquiWS_PortType puerto = servicio.getAdquiWS();           
                Map[] datos=puerto.getPartidas(String.valueOf(gestion));
                this.JC_Partidas.addItem("- ELIJA UNA PARTIDA -");
                if (datos!=null){
                    for (int c=0;c<datos.length;c++){
                        this.JC_Partidas.addItem(datos[c].get("PARTIDA")+" - "+datos[c].get("DETALLE") );
                    }
                }
            }
            catch (RemoteException e){
                javax.swing.JOptionPane.showMessageDialog(this,"<html> error de conexion con el servidor <br> "+e,"SYSTEM CAPRICORN",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            catch (ServiceException e){ System.out.println(e);}
    }
    public void getDataItems(){
        try {
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            Map[] datos=puerto.getItem(this.cod_item);
            if(datos!=null){
                System.out.println("Con datos :D");
                this.articulo = datos[0].get("ARTICULO").toString();
                this.unidad_medida = datos[0].get("UNIDAD_MEDIDA").toString();
                this.cod_tipo_item = Integer.parseInt(datos[0].get("COD_TIPO_ITEM").toString());
                System.out.println("Magico señores  articulo: "+this.articulo+", unidad_medida: "+this.unidad_medida+", cod_tipo_item: "+this.cod_tipo_item);
//                for (int c=0;c<datos.length;c++){
//                    
//                }
            }
            else{
                System.out.println("Vacio :P");
            }
        } catch (Exception e) {
            System.out.println("Error: "+e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JB_ActualizaItem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTA_Descripcion = new javax.swing.JTextArea();
        JC_Partidas = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        JB_ActualizaItem.setText("Actualizar");
        JB_ActualizaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ActualizaItemActionPerformed(evt);
            }
        });

        JTA_Descripcion.setColumns(20);
        JTA_Descripcion.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        JTA_Descripcion.setRows(5);
        JTA_Descripcion.setText("bvfbc");
        jScrollPane1.setViewportView(JTA_Descripcion);

        JC_Partidas.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        JC_Partidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JC_PartidasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(JC_Partidas, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(JB_ActualizaItem)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JC_Partidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(JB_ActualizaItem)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addItem(int partida,String articulo,String unidad_medida, int cod_tipo_item){
        try {
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            String cod_item = puerto.getSEC_COD_ITEM();
            System.out.println("El cod_item a usar es: "+cod_item);
            puerto.addItems("ADD-insDataItm", Integer.parseInt(cod_item),partida, articulo, unidad_medida, this.gestion, "V", cod_tipo_item);
            puerto.updateItemPPTO(this.cod_trans_detalle, cod_item, unidad_medida);
            this.setVisible(false);
        } catch (Exception e) {
            System.out.println("Error: "+e);
        }
    }
    private void JB_ActualizaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ActualizaItemActionPerformed
        // TODO add your handling code here:
        int dialogResult = javax.swing.JOptionPane.showConfirmDialog (this, "¿Esta seguro(a) de cambiar la partida al item?","CAMBIO DE ITEM",javax.swing.JOptionPane.YES_NO_OPTION);
        if(dialogResult == javax.swing.JOptionPane.YES_OPTION){
//            String partida = this.JTF_Partida.getText();
            if(!"".equals(partida)){
                try {
                    this.addItem(Integer.parseInt(partida), this.articulo, this.unidad_medida, this.cod_tipo_item);
                } catch (Exception e) {
                    javax.swing.JOptionPane.showMessageDialog(this,
                    "Debe Seleccionar una partida" ,
                    "SYSTEM CAPRICORN", javax.swing.JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
            }else{
                javax.swing.JOptionPane.showMessageDialog(this,
                "Debe introducir una partida valida" ,
                "SYSTEM CAPRICORN", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            
        }
    }//GEN-LAST:event_JB_ActualizaItemActionPerformed
    private String getDescripcion(String partida){
        System.out.println("Buscando Partida....");
        try {
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            String descripcion = puerto.getDescPartida(partida);
            if(descripcion.equals(""))
                return "Sin Descripción";
            else
                return descripcion;
        } catch (Exception e) {
            return null;
        }
        
    }
    private void JC_PartidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JC_PartidasActionPerformed
        // TODO add your handling code here:
        //System.out.println("Sacatelas Babuchas --> "+this.JC_Partidas.getSelectedItem());
        String partida = this.JC_Partidas.getSelectedItem().toString().split(" - ")[0];
        this.partida=partida;
        this.JTA_Descripcion.setText(getDescripcion(partida));
        //this.JC_Partidas.getSelectedItem();
    }//GEN-LAST:event_JC_PartidasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JD_CambiaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JD_CambiaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JD_CambiaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JD_CambiaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JD_CambiaPartida dialog = new JD_CambiaPartida(new javax.swing.JFrame(), true,null, null,0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_ActualizaItem;
    private javax.swing.JComboBox JC_Partidas;
    private javax.swing.JTextArea JTA_Descripcion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
