/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package umsa.capricornio.gui.transacciones;

import java.util.Map;
import javax.swing.event.TableModelEvent;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import umsa.capricornio.gui.ConnectADQUI.AdquiWSServiceLocator;
import umsa.capricornio.gui.ConnectADQUI.AdquiWS_PortType;
import umsa.capricornio.gui.transacciones.Adquisiciones.BancoProveedor.tablas.TablaProveedoresBusca;
import umsa.capricornio.gui.transacciones.tablas.TablaItemsPartidas;
import umsa.capricornio.utilitarios.herramientas.MiRenderer;

/**
 *
 * @author UMSA-JES
 */
public class JD_CambiaItem extends javax.swing.JDialog {

    TablaItemsPartidas partida_item;
//    TablaProveedoresBusca pbusca;
    /**
     * Creates new form JD_CambiaItem
     */
    String cod_trans_detalle;
    String cod_item;
    public JD_CambiaItem(java.awt.Frame parent, boolean modal, String cod_trans_detalle, String cod_item) {
        super(parent, modal);
        initComponents();
        ConstruyeTablaItemsPartida();
        this.setLocationRelativeTo(null);
        this.setTitle("Buscador de Items");
        this.cod_trans_detalle = cod_trans_detalle;
        this.cod_item = cod_item;
//        Llena();
        
    }

    public void BuscaItems(String partida){
        CerearTablaIP();
        try {
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            Map[] datos=puerto.getItemsPart(partida);
            System.out.println("Aqui va");
            System.out.println("eooooo el tamaño es: "+datos.length);
            if (datos!=null){
                for (int c=0;c<datos.length;c++){
                    partida_item.insert(c);
                    TblPartidasItem.tableChanged(new TableModelEvent(partida_item, c, c, TableModelEvent.ALL_COLUMNS,TableModelEvent.INSERT));
                    TblPartidasItem.setValueAt(datos[c].get("COD_ITEM"),c,0);
                    TblPartidasItem.setValueAt(datos[c].get("PARTIDA"),c,1);
                    TblPartidasItem.setValueAt(datos[c].get("DETALLE"),c,2);                    
                    TblPartidasItem.setValueAt(datos[c].get("ARTICULO"),c,3);
                    TblPartidasItem.setValueAt(datos[c].get("UNIDAD_MEDIDA"),c,4);
                }
            }
            else
                System.out.println("VACIO !!!!!!!");
        } catch (Exception e) {
            System.out.println("noooooooooo --> "+e);
        }
        
    }
    public void ConstruyeTablaItemsPartida(){
        
        partida_item = new TablaItemsPartidas();
//        pbusca = new TablaProveedoresBusca();
        TblPartidasItem.setAutoCreateColumnsFromModel(false);
        TblPartidasItem.setModel(partida_item);

        for (int k = 0; k < TablaItemsPartidas.m_columns.length; k++) {
//            System.out.println("Okey Micky Mouse :P "+k);
            TableCellRenderer renderer = new MiRenderer(TablaItemsPartidas.m_columns[k].m_alignment);
            /*DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
            renderer.setHorizontalAlignment(DatosTablaObligacionBandeja.m_columns[k].m_alignment);*/
            TableColumn column = new TableColumn(k, TablaItemsPartidas.m_columns[k].m_width, renderer, null);
            TblPartidasItem.addColumn(column);
        }
        JTableHeader header = TblPartidasItem.getTableHeader();
        header.setUpdateTableInRealTime(true);
        header.setReorderingAllowed(true);
        JSPItemPartida.getViewport().add(TblPartidasItem);
    }
    void CerearTablaIP(){
        int f = TblPartidasItem.getRowCount();
        for (int i=f-1;i>=0;i--){
             if (partida_item.delete(i)) {
                TblPartidasItem.tableChanged(new TableModelEvent(
                partida_item, i, i, TableModelEvent.ALL_COLUMNS, TableModelEvent.INSERT));
             }
        }
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JT_Partida = new javax.swing.JTextField();
        JB_Buscar = new javax.swing.JButton();
        JSPItemPartida = new javax.swing.JScrollPane();
        TblPartidasItem = new javax.swing.JTable();
        JB_CItem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("Ingrese Partida:");

        JB_Buscar.setText("Buscar");
        JB_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_BuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JT_Partida, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 392, Short.MAX_VALUE)
                .addComponent(JB_Buscar)
                .addGap(52, 52, 52))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JT_Partida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_Buscar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        JSPItemPartida.setViewportView(TblPartidasItem);

        JB_CItem.setText("Cambiar Item");
        JB_CItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JSPItemPartida)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(JB_CItem)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JSPItemPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JB_CItem)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_BuscarActionPerformed
        // TODO add your handling code here:
        
        BuscaItems(this.JT_Partida.getText());
    }//GEN-LAST:event_JB_BuscarActionPerformed

    private void JB_CItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CItemActionPerformed
        // TODO add your handling code here:
         int fila = TblPartidasItem.getSelectedRow();
        if (fila<0){
//            System.out.println("Sin selección");
            javax.swing.JOptionPane.showMessageDialog(this,
            "Debe seleccionar un item" ,
            "SYSTEM CAPRICORN", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }
            
        String cod_item = String.valueOf(TblPartidasItem.getValueAt(fila,0));
        String unidad_medida = String.valueOf(TblPartidasItem.getValueAt(fila,4));
        System.out.println("El cod_item es: "+cod_item+" y el la unidad de medida es: "+unidad_medida);
        int dialogResult = javax.swing.JOptionPane.showConfirmDialog (this, "¿Esta seguro(a) de cambiar el item?","CAMBIO DE ITEM",javax.swing.JOptionPane.YES_NO_OPTION);
        if(dialogResult == javax.swing.JOptionPane.YES_OPTION){
            try {
                AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
                AdquiWS_PortType puerto = servicio.getAdquiWS();
                System.out.println("WOOOPAAA1");
                puerto.updateItemPPTO(this.cod_trans_detalle, cod_item, unidad_medida);
                System.out.println("WOOOPAAA2");
                this.setVisible(false);
            } catch (Exception e) {
                System.out.println("NOPI :(");
//                javax.swing.JOptionPane.showMessageDialog(this,
//                "ERROR EN EL SERVIDOR "+e ,
//                "SYSTEM CAPRICORN", javax.swing.JOptionPane.ERROR_MESSAGE);
////                return;
            }
        }
        else
            return;
    }//GEN-LAST:event_JB_CItemActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JD_CambiaItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JD_CambiaItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JD_CambiaItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JD_CambiaItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JD_CambiaItem dialog = new JD_CambiaItem(new javax.swing.JFrame(), true,null,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Buscar;
    private javax.swing.JButton JB_CItem;
    private javax.swing.JScrollPane JSPItemPartida;
    private javax.swing.JTextField JT_Partida;
    private javax.swing.JTable TblPartidasItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
