/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DiagBuscaItems.java
 *
 * Created on 28-07-2011, 05:13:01 PM
 */
package umsa.capricornio.gui.transacciones.XXXIngresoMateriales;

import java.awt.event.KeyEvent;
import java.rmi.RemoteException;
import java.util.Map;
import javax.swing.event.TableModelEvent;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.xml.rpc.ServiceException;
import umsa.capricornio.domain.Items;
import umsa.capricornio.gui.ConnectADQUI.AdquiWSServiceLocator;
import umsa.capricornio.gui.ConnectADQUI.AdquiWS_PortType;
import umsa.capricornio.gui.menu.FrmMenu;
import umsa.capricornio.gui.transacciones.XXXIngresoMateriales.tabla.XXXTablaItemsBusca;
import umsa.capricornio.utilitarios.herramientas.MiRenderer;

/**
 *
 * @author julian
 */
public class XXXDiagBuscaItems extends javax.swing.JDialog {
    private boolean sw;

    XXXTablaItemsBusca items;
    int cod_almacen;
    private Runtime r;
    private Items item;
    /** Creates new form DiagBuscaItems */
    public XXXDiagBuscaItems(FrmMenu menu,int cod_almacen) {
        super(menu, true);
        initComponents();
        ConstruyeTablaItems();
        this.cod_almacen=cod_almacen;
    }
    
    private void ConstruyeTablaItems(){
        items = new XXXTablaItemsBusca();
        TblItems.setAutoCreateColumnsFromModel(false);
        TblItems.setModel(items);

        for (int k = 0; k < XXXTablaItemsBusca.m_columns.length; k++) {
            TableCellRenderer renderer = new MiRenderer(XXXTablaItemsBusca.m_columns[k].m_alignment);
            /*DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
            renderer.setHorizontalAlignment(DatosTablaObligacionBandeja.m_columns[k].m_alignment);*/
            TableColumn column = new TableColumn(k, XXXTablaItemsBusca.m_columns[k].m_width, renderer, null);
            TblItems.addColumn(column);
        }
        JTableHeader header = TblItems.getTableHeader();
        header.setUpdateTableInRealTime(true);
        header.setReorderingAllowed(true);
        PnlItems.getViewport().add(TblItems);
    }
        
    void CerearTablaItems(){
        int f = TblItems.getRowCount();
        for (int i=f-1;i>=0;i--){
             if (items.delete(i)) {
                TblItems.tableChanged(new TableModelEvent(
                items, i, i, TableModelEvent.ALL_COLUMNS, TableModelEvent.INSERT));
             }
        }
    }    
        
    void AbreDialogo(){
        setVisible(true);
    }
    
    boolean AceptaDatos(){
        
        return sw;
    }
    
    Items ItemSeleccionado(){
        return item;
    }
        
    void cierraFrm(){
        System.gc();
        r = Runtime.getRuntime();
        long mem1 = r.freeMemory();
        dispose();
    }
    
    void ElejirItem(){
        int fila = TblItems.getSelectedRow();
        item = new Items();
        item.setCod_item(Integer.parseInt(TblItems.getValueAt(fila, 0).toString()));
        item.setUnidad_medida(TblItems.getValueAt(fila, 1).toString());
        item.setTipo_item(TblItems.getValueAt(fila, 2).toString());
        item.setArticulo(TblItems.getValueAt(fila, 3).toString());
        sw=true;
        cierraFrm();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtItem = new javax.swing.JTextField();
        PnlItems = new javax.swing.JScrollPane();
        TblItems = new javax.swing.JTable();
        BtnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TreTransaccion = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        TxtItem.setFont(new java.awt.Font("Arial", 0, 11));
        TxtItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtItemKeyPressed(evt);
            }
        });
        getContentPane().add(TxtItem);
        TxtItem.setBounds(50, 20, 320, 20);

        TblItems.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TblItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TblItemsMousePressed(evt);
            }
        });
        TblItems.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TblItemsKeyPressed(evt);
            }
        });
        PnlItems.setViewportView(TblItems);

        getContentPane().add(PnlItems);
        PnlItems.setBounds(22, 60, 490, 160);

        BtnBuscar.setFont(new java.awt.Font("Arial", 0, 11));
        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnBuscar);
        BtnBuscar.setBounds(400, 20, 110, 23);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Transaccion");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("colors");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("violet");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("red");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("yellow");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("sports");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("basketball");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("soccer");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("football");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("hockey");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        TreTransaccion.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        TreTransaccion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(TreTransaccion);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 230, 110, 210);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-554)/2, (screenSize.height-554)/2, 554, 554);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        String articulo = TxtItem.getText().trim();
        if ("".equals(articulo)){
            javax.swing.JOptionPane.showMessageDialog(this,"Debe introducir alguna palabra","SYSTEM CAPRICORN",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
            
        try{
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            Map[] datos=puerto.getBuscaItems(articulo);  
            CerearTablaItems();
            if (datos!=null){
                for (int c=0;c<datos.length;c++){
                    items.insert(c);
                    TblItems.tableChanged(new TableModelEvent(items, c, c, TableModelEvent.ALL_COLUMNS,TableModelEvent.INSERT));
                    TblItems.setValueAt(datos[c].get("COD_ITEM"),c,0);
                    TblItems.setValueAt(datos[c].get("UNIDAD_MEDIDA"),c,1);                    
                    TblItems.setValueAt(datos[c].get("TIPO_ITEM"),c,2);
                    TblItems.setValueAt(datos[c].get("ARTICULO"),c,3);                    
                }
            }
        }
        catch (RemoteException e){
            javax.swing.JOptionPane.showMessageDialog(this,"<html> error de conexion con el servidor <br> "+e,"SYSTEM CAPRICORN",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        catch (ServiceException e){ System.out.println(e);}  
        TxtItem.setText("");
        TblItems.requestFocus();
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void TblItemsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblItemsMousePressed
    if (evt.getClickCount() == 2) {        
        ElejirItem();
    }
    }//GEN-LAST:event_TblItemsMousePressed

    private void TblItemsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TblItemsKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER )  {
            ElejirItem();
        }
    }//GEN-LAST:event_TblItemsKeyPressed

    private void TxtItemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtItemKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER )  {
            BtnBuscar.doClick();
        }
    }//GEN-LAST:event_TxtItemKeyPressed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JScrollPane PnlItems;
    private javax.swing.JTable TblItems;
    private javax.swing.JTree TreTransaccion;
    private javax.swing.JTextField TxtItem;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
