/**
 * AdquiWS_PortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package umsa.capricornio.gui.ConnectADQUI;

public interface AdquiWS_PortType extends java.rmi.Remote {
    public java.util.HashMap[] getRoles() throws java.rmi.RemoteException;
    public java.util.HashMap[] setItems(java.lang.String tran, int partida, java.lang.String articulo, java.lang.String unidad_medida, int gestion, java.lang.String estado, int cod_tipo_item) throws java.rmi.RemoteException;
    public java.util.HashMap[] setGestion(java.lang.String tran, int gestion) throws java.rmi.RemoteException;
    public java.lang.String getDetalle(java.lang.String tran, int cod_complemento) throws java.rmi.RemoteException;
    public java.util.HashMap[] getReporteOrdenDescargo(int cod_transaccion, java.lang.String estado, int cod_tramite) throws java.rmi.RemoteException;
    public java.util.HashMap[] setPartida(java.lang.String tran, int cod_trans_detalle, java.lang.String partida) throws java.rmi.RemoteException;
    public java.util.HashMap[] getTotal2(int cod_transaccion) throws java.rmi.RemoteException;
    public java.util.HashMap[] getTramite(int cod_tramite) throws java.rmi.RemoteException;
    public java.lang.String getNombreUsuario2(java.lang.String cod_trans_nro) throws java.rmi.RemoteException;
    public java.util.HashMap[] getReporteNotaConformidadx(int cod_trans_nro, java.lang.String estado, int cod_tramite) throws java.rmi.RemoteException;
    public java.util.HashMap[] getReporteOrden(int cod_trans_nro, java.lang.String estado, int cod_tramite) throws java.rmi.RemoteException;
    public java.util.HashMap[] getReportePedidox(int cod_trans_nro, java.lang.String estado, int cod_tramite) throws java.rmi.RemoteException;
    public java.lang.String getNombreUsuario1(java.lang.String cod_transaccion) throws java.rmi.RemoteException;
    public java.util.HashMap[] getReporteSolicitudx(int cod_transaccion, java.lang.String estado, int cod_tramite) throws java.rmi.RemoteException;
    public java.util.HashMap[] getReporteSolicitudBorrador2(int cod_transaccion) throws java.rmi.RemoteException;
    public java.util.HashMap[] getReporteOrdenDescargox(int cod_transaccion, java.lang.String estado, int cod_tramite) throws java.rmi.RemoteException;
    public java.util.HashMap[] getReporteOrdenx(int cod_trans_nro, java.lang.String estado, int cod_tramite) throws java.rmi.RemoteException;
    public java.util.HashMap[] getUsuario(java.lang.String apodo, java.lang.String clave) throws java.rmi.RemoteException;
    public java.util.HashMap[] getUsuario() throws java.rmi.RemoteException;
    public java.util.HashMap[] setUsuario(java.lang.String tran, java.lang.String apodo, java.lang.String clave, java.lang.String usuario, java.lang.String nombre_resumen) throws java.rmi.RemoteException;
    public java.util.HashMap[] getGestion(int gestion) throws java.rmi.RemoteException;
    public java.util.HashMap[] getGestion() throws java.rmi.RemoteException;
    public java.util.HashMap[] getUnidadEjecutora(int gestion) throws java.rmi.RemoteException;
    public java.util.HashMap[] setTransaccionDetalleNro(java.lang.String tran, int cod_trans_detalle, int cod_trans_nro) throws java.rmi.RemoteException;
    public java.util.HashMap[] getBuscaItems(java.lang.String articulo) throws java.rmi.RemoteException;
    public java.util.HashMap[] getPartida(int gestion) throws java.rmi.RemoteException;
    public java.util.HashMap[] getTipoItem() throws java.rmi.RemoteException;
    public java.util.HashMap[] getUnidadMedida() throws java.rmi.RemoteException;
    public java.util.HashMap[] setProponenteADJ2(int cod_transaccion, java.lang.String cod_proveedor, java.lang.String nombre, java.lang.String nombre_comercial, java.lang.String direccion, java.lang.String telefono) throws java.rmi.RemoteException;
    public java.util.HashMap[] getNroOrdenCompra(int cod_transaccion) throws java.rmi.RemoteException;
    public java.util.HashMap[] setCreaNroTramite(java.lang.String tran, int cod_transaccion, int cod_almacen, int cod_tramite, int gestion, int cod_trans_nro, int cod_usuario) throws java.rmi.RemoteException;
    public java.util.HashMap[] getItems2(int cod_transaccion) throws java.rmi.RemoteException;
    public java.util.HashMap[] getItems2(int cod_transaccion, int cod_tramite) throws java.rmi.RemoteException;
    public java.util.HashMap[] addProponenteDescargo(java.lang.String cod_proveedor, int cod_transaccion, int cod_trans_nro, java.lang.String tipo, java.lang.String clase, java.lang.String nombre, java.lang.String nombre_comercial, java.lang.String direccion, java.lang.String telefono, java.lang.String adh_nombre) throws java.rmi.RemoteException;
    public java.util.HashMap[] updateProponenteDescargo(int cod_transaccion, int cod_trans_nro, java.lang.String cod_proveedor, java.lang.String tipo, java.lang.String clase, java.lang.String nombre, java.lang.String nombre_comercial, java.lang.String direccion, java.lang.String telefono, java.lang.String adh_nombre) throws java.rmi.RemoteException;
    public java.util.HashMap[] setDetallePrecioUnit(java.lang.String tran, int cod_trans_detalle, double precio_unit) throws java.rmi.RemoteException;
    public java.util.HashMap[] getProponenteADJ2(int cod_transaccion) throws java.rmi.RemoteException;
    public java.util.HashMap[] addUnidadMedida(java.lang.String tran, int cod_unidad_medida, java.lang.String detalle) throws java.rmi.RemoteException;
    public java.util.HashMap[] getBuscaItemsx(int gestion, java.lang.String articulo) throws java.rmi.RemoteException;
    public java.util.HashMap[] addDetalle(java.lang.String tran, int cod_complemento, int cod_trans_detalle, java.lang.String detalle) throws java.rmi.RemoteException;
    public java.util.HashMap[] delDetalle(java.lang.String tran, int cod_complemento, int cod_trans_detalle) throws java.rmi.RemoteException;
    public java.util.HashMap[] updateDetallex(java.lang.String tran, int cod_complemento, java.lang.String detalle) throws java.rmi.RemoteException;
    public void delItemPro(java.lang.String tran, int cod_trans_detalle) throws java.rmi.RemoteException;
    public java.util.HashMap[] updateItemx2(java.lang.String tran, java.lang.String cod_trans_detalle, java.lang.String detalle, int cod_unidad_medida, int cantidad_pedido, java.lang.String partida, double precio_unit, int cod_item) throws java.rmi.RemoteException;
    public java.util.HashMap[] loadDetalle(int cod_trans_detalle) throws java.rmi.RemoteException;
    public java.util.HashMap[] getProveedores() throws java.rmi.RemoteException;
    public java.util.HashMap[] eliminaFecha(int x) throws java.rmi.RemoteException;
    public java.util.HashMap[] setFechasNH(java.lang.String x) throws java.rmi.RemoteException;
    public java.util.HashMap[] getFechasNH() throws java.rmi.RemoteException;
    public java.util.HashMap[] setFechasModif(int y, java.lang.String x) throws java.rmi.RemoteException;
    public java.util.HashMap[] getDetProveedores(java.lang.String cod) throws java.rmi.RemoteException;
    public java.util.HashMap[] getUsuario2(java.lang.String apodo, java.lang.String clave) throws java.rmi.RemoteException;
    public java.util.HashMap[] getFechaServ() throws java.rmi.RemoteException;
    public java.util.HashMap[] getUsuarioRol(int cod_usuario) throws java.rmi.RemoteException;
    public java.util.HashMap[] getEnlaces(int cod_rol) throws java.rmi.RemoteException;
    public java.util.HashMap[] getPasswordUsr(java.lang.String tran, int cod_usuario, java.lang.String pswant, java.lang.String pswnue) throws java.rmi.RemoteException;
    public java.util.HashMap[] getPasswordUsr(java.lang.String tran, int cod_usuario, java.lang.String pswnue) throws java.rmi.RemoteException;
    public java.util.HashMap[] getVerifPassw(int cod_usuario, java.lang.String pswant) throws java.rmi.RemoteException;
    public java.util.HashMap[] getAlmacen(int gestion) throws java.rmi.RemoteException;
    public java.util.HashMap[] setAlmacen(java.lang.String tran, java.lang.String almacen, java.lang.String facultad, java.lang.String cod_fac, int gestion) throws java.rmi.RemoteException;
    public java.util.HashMap[] setAlmacenModif(java.lang.String tran, int cod_almacen, java.lang.String almacen, java.lang.String facultad, java.lang.String cod_fac, int gestion) throws java.rmi.RemoteException;
    public java.util.HashMap[] setAlmacenDel(java.lang.String tran, int cod_almacen, int gestion) throws java.rmi.RemoteException;
    public java.util.HashMap[] getDa(int gestion) throws java.rmi.RemoteException;
    public java.util.HashMap[] getUsuariox(int gestion, int cod_almacen) throws java.rmi.RemoteException;
    public java.util.HashMap[] getUsuariox2(int gestion, int cod_almacen) throws java.rmi.RemoteException;
    public java.util.HashMap[] getUsuariosTipo(int cod_rol, int gestion) throws java.rmi.RemoteException;
    public java.util.HashMap[] getUsuarios() throws java.rmi.RemoteException;
    public int secCodUsuario() throws java.rmi.RemoteException;
    public java.util.HashMap[] setUsuariox(java.lang.String tran, int cod_usuario, java.lang.String apodo, java.lang.String clave, java.lang.String usuario, java.lang.String nombre_resumen) throws java.rmi.RemoteException;
    public java.util.HashMap[] addUserApert(java.lang.String tran, int cod_usuario, java.lang.String cod_apert, int gestion) throws java.rmi.RemoteException;
    public java.util.HashMap[] setUsuarioModif(java.lang.String tran, int cod_usuario, java.lang.String usuario, java.lang.String nombre_resumen) throws java.rmi.RemoteException;
    public java.util.HashMap[] setUsuarioDel(java.lang.String tran, int cod_usuario) throws java.rmi.RemoteException;
    public java.util.HashMap[] getUnidadEjecutora1(int gestion) throws java.rmi.RemoteException;
    public java.util.HashMap[] getUnidadEjecutora2(int gestion, int cod_almacen) throws java.rmi.RemoteException;
    public java.util.HashMap[] setUnidadEjecutora(java.lang.String tran, java.lang.String cod_apert, java.lang.String unidad_ejecutora, java.lang.String apertura, int cod_almacen, java.lang.String cod_da, int gestion) throws java.rmi.RemoteException;
    public java.util.HashMap[] setUnidadEjecutoraModif(java.lang.String tran, java.lang.String cod_apert, java.lang.String unidad_ejecutora, java.lang.String apertura, int cod_almacen, java.lang.String cod_da, int gestion) throws java.rmi.RemoteException;
    public java.util.HashMap[] setUnidadEjecutoraDel(java.lang.String tran, java.lang.String cod_apert) throws java.rmi.RemoteException;
    public java.util.HashMap[] getItemsABM(int gestion, int partida) throws java.rmi.RemoteException;
    public java.util.HashMap[] setItemsModif(java.lang.String tran, int cod_item, java.lang.String articulo, java.lang.String unidad_medida, int cod_tipo_item, int gestion) throws java.rmi.RemoteException;
    public java.util.HashMap[] setItemsDel(java.lang.String tran, int cod_item) throws java.rmi.RemoteException;
    public java.util.HashMap[] getGrupoItem() throws java.rmi.RemoteException;
    public java.util.HashMap[] getSubGrupoItem(java.lang.String grupo) throws java.rmi.RemoteException;
    public java.util.HashMap[] setGestionModif(java.lang.String tran, int cod_gestion, int gestion) throws java.rmi.RemoteException;
    public java.util.HashMap[] getUsrRol() throws java.rmi.RemoteException;
    public java.util.HashMap[] getUsrRol2(int cod_almacen) throws java.rmi.RemoteException;
    public java.util.HashMap[] getUsrFirma(int cod_almacen) throws java.rmi.RemoteException;
    public java.util.HashMap[] setUsrRol(java.lang.String tran, int cod_usuario, int cod_rol) throws java.rmi.RemoteException;
    public java.util.HashMap[] setUsrRolDel(java.lang.String tran, int cod_usuario, int cod_rol) throws java.rmi.RemoteException;
    public java.util.HashMap[] getUsrUnidad(int gestion, int cod_almacen) throws java.rmi.RemoteException;
    public java.util.HashMap[] setUsrUnidad(java.lang.String tran, int cod_usuario, java.lang.String cod_unidad, int gestion) throws java.rmi.RemoteException;
    public java.util.HashMap[] setUsrUnidadDel(java.lang.String tran, int cod_usuario, java.lang.String cod_unidad, int gestion) throws java.rmi.RemoteException;
    public java.util.HashMap[] getUsrWorkflow() throws java.rmi.RemoteException;
    public java.util.HashMap[] getUsrWorkflow2(int cod_almacen) throws java.rmi.RemoteException;
    public java.util.HashMap[] getWorkflowDetalle() throws java.rmi.RemoteException;
    public java.util.HashMap[] getEstadosWorkflow(int cod_w) throws java.rmi.RemoteException;
    public java.util.HashMap[] setUsrWorkflow(int cod_usuario, int cod_w, java.lang.String cod_estado) throws java.rmi.RemoteException;
    public java.util.HashMap[] setUsrWorkflowDel(int cod_usuario, int cod_w, java.lang.String cod_estado) throws java.rmi.RemoteException;
    public java.util.HashMap[] setProveedorCrea(java.lang.String tran, java.lang.String casa_comercial, java.lang.String servicio, java.lang.String direccion, java.lang.String partida, java.lang.String telefono, java.lang.String fax, java.lang.String web, java.lang.String nit, java.lang.String gran_act, java.lang.String razon_soc) throws java.rmi.RemoteException;
    public java.util.HashMap[] setProveedorActualiza(java.lang.String tran, int cod_proveedor, java.lang.String casa_comercial, java.lang.String servicio, java.lang.String direccion, java.lang.String partida, java.lang.String telefono, java.lang.String fax, java.lang.String web, java.lang.String nit, java.lang.String gran_act, java.lang.String razon_soc, java.lang.String estado) throws java.rmi.RemoteException;
    public java.util.HashMap[] setProveedorElimina(java.lang.String tran, int cod_proveedor) throws java.rmi.RemoteException;
    public java.util.HashMap[] getProveedoresBusqueda(java.lang.String partida, java.lang.String casa, java.lang.String servicio, java.lang.String nit) throws java.rmi.RemoteException;
    public java.util.HashMap[] getSansiones(int cod_proveedor) throws java.rmi.RemoteException;
    public java.util.HashMap[] setProveedorSansion(java.lang.String tran, int cod_proveedor, java.lang.String fec_ini, java.lang.String fec_fin, java.lang.String obs) throws java.rmi.RemoteException;
    public java.util.HashMap[] setProveedorSansionMod(java.lang.String tran, int cod_prov_sansion, java.lang.String fec_ini, java.lang.String fec_fin, java.lang.String obs) throws java.rmi.RemoteException;
    public java.util.HashMap[] setProveedorSansionElim(java.lang.String tran, int cod_prov_sansion) throws java.rmi.RemoteException;
    public java.util.HashMap[] getEst(int cod_trans_nro) throws java.rmi.RemoteException;
    public java.util.HashMap[] getTramites() throws java.rmi.RemoteException;
    public java.util.HashMap[] getTransaccionBandeja(int gestion, int cod_almacen, int cod_usuario, int cod_w, java.lang.String cod_estado, int cod_tramite) throws java.rmi.RemoteException;
    public java.util.HashMap[] getTransaccionBandejaUnion(int gestion, int cod_almacen, int cod_tramite, int cod_usuario) throws java.rmi.RemoteException;
    public java.util.HashMap[] getTransaccionesBuscaAdquisicion(int cod_almacen, int cod_usuario, int cod_tramite, int gestion, java.lang.String solicitud, java.lang.String hoja_ruta, java.lang.String preventivo) throws java.rmi.RemoteException;
    public java.util.HashMap[] getTransaccionesBuscaAdquisicionTODO(int cod_almacen, int cod_usuario, int cod_tramite, int gestion) throws java.rmi.RemoteException;
    public java.util.HashMap[] getTransaccionesBuscaAdquisicionTODO2(int cod_almacen, int cod_usuario, int cod_tramite, int gestion) throws java.rmi.RemoteException;
    public java.util.HashMap[] getTransaccionEstado(int cod_almacen, int cod_tramite, int gestion, int inicio, int fin) throws java.rmi.RemoteException;
    public java.util.HashMap[] getTransaccionBandejaAdqui(int gestion, int cod_almacen, int cod_usuario, int cod_tramite) throws java.rmi.RemoteException;
    public java.util.HashMap[] busquedaAdquiOrdenC(int gestion, int cod_almacen, int cod_tramite, java.lang.String nro, java.lang.String hoja_ruta) throws java.rmi.RemoteException;
    public java.util.HashMap[] getNroTransacciones(int gestion, int cod_tramite, int cod_almacen) throws java.rmi.RemoteException;
    public java.util.HashMap[] getTieneTipoTramite(int cod_tramite, int cod_trans_detalle) throws java.rmi.RemoteException;
    public java.util.HashMap[] setCreaNroTramiteDos(java.lang.String tran, int cod_transaccion, int cod_almacen, int cod_tramite, int gestion, int cod_trans_nro, int cod_usuario) throws java.rmi.RemoteException;
    public java.util.HashMap[] setCreaNroTramiteTres(java.lang.String tran, int cod_transaccion, int cod_almacen, int cod_tramite, int gestion, int cod_trans_nro, int cod_usuario) throws java.rmi.RemoteException;
    public java.util.HashMap[] setNumIngreso(java.lang.String tran, int cod_trans_nro) throws java.rmi.RemoteException;
    public java.lang.String setTransaccionesDestino(java.lang.String tran, int cod_trans_detalle, int cod_w, java.lang.String origen) throws java.rmi.RemoteException;
    public java.util.HashMap[] setTransaccionesOrigen(java.lang.String tran, int cod_trans_detalle, int cod_w, java.lang.String destino) throws java.rmi.RemoteException;
    public java.util.HashMap[] setTransaccionesPptoUnidad(java.lang.String tran, int cod_trans_detalle, java.lang.String origen) throws java.rmi.RemoteException;
    public java.util.HashMap[] getReporteSolicitud(int cod_transaccion, java.lang.String estado, int cod_tramite) throws java.rmi.RemoteException;
    public java.util.HashMap[] getReporteSolicitudBorrador(int cod_transaccion) throws java.rmi.RemoteException;
    public java.util.HashMap[] getReporteSolicitud2(int cod_transaccion) throws java.rmi.RemoteException;
    public java.util.HashMap[] getReporteIngreso(int cod_trans_nro, java.lang.String estado, int cod_tramite) throws java.rmi.RemoteException;
    public java.util.HashMap[] getReporteIngresox(int cod_trans_nro, java.lang.String estado, int cod_tramite) throws java.rmi.RemoteException;
    public java.util.HashMap[] getReportePedido(int cod_trans_nro, java.lang.String estado, int cod_tramite) throws java.rmi.RemoteException;
    public java.util.HashMap[] getDias(int cod) throws java.rmi.RemoteException;
    public java.util.HashMap[] setDias(int cod, int d) throws java.rmi.RemoteException;
    public java.util.HashMap[] getReporteNotaConformidad(int cod_trans_nro, java.lang.String estado, int cod_tramite) throws java.rmi.RemoteException;
    public java.util.HashMap[] getReportePedido2(int cod_trans_nro, java.lang.String estado, int cod_tramite) throws java.rmi.RemoteException;
    public java.util.HashMap[] getTransaccion(int cod_transaccion) throws java.rmi.RemoteException;
    public java.util.HashMap[] getTransaccionNro(int cod_trans_nro) throws java.rmi.RemoteException;
    public java.util.HashMap[] getItemsPorOrdenDeCompra(int cod_trans_nro) throws java.rmi.RemoteException;
    public java.util.HashMap[] getItemsPorOrdenDeCompra2(int cod_trans_nro) throws java.rmi.RemoteException;
    public java.util.HashMap[] getDocumentos(int cod_transaccion) throws java.rmi.RemoteException;
    public java.util.HashMap[] getUltimoDocumento() throws java.rmi.RemoteException;
    public java.util.HashMap[] setDocumentos(java.lang.String tran, int cod_transaccion, java.lang.String terminos_ref, java.lang.String ubicacion, java.lang.String descripcion, java.lang.String estado, int cod_adjunto) throws java.rmi.RemoteException;
    public java.util.HashMap[] setAnulaDocumento(java.lang.String tran, int cod_documento) throws java.rmi.RemoteException;
    public java.util.HashMap[] setNuevoComplemento(java.lang.String tran, int cod_complemento, java.lang.String detalle_adqui) throws java.rmi.RemoteException;
    public java.util.HashMap[] setNuevoComplementoIngAlm(java.lang.String tran, int cod_complemento, java.lang.String detalle_alm) throws java.rmi.RemoteException;
    public java.util.HashMap[] setDetalleDBC(java.lang.String tran, int cod_trans_detalle, java.lang.String dbc) throws java.rmi.RemoteException;
    public java.util.HashMap[] setDetalleContrato(java.lang.String tran, int cod_trans_detalle, java.lang.String contrato) throws java.rmi.RemoteException;
    public java.util.HashMap[] XAnulaTramite(java.lang.String tran, int nro) throws java.rmi.RemoteException;
    public java.util.HashMap[] getTransDetalle(int nro) throws java.rmi.RemoteException;
    public java.util.HashMap[] setActualizaTransaccionAlm(int cod_transaccion, java.lang.String obs_almacen) throws java.rmi.RemoteException;
    public java.util.HashMap[] setActualizaTransaccionAlmDos(int cod_trans_nro, java.lang.String obs_almacen) throws java.rmi.RemoteException;
    public java.util.HashMap[] setActualizaTransaccionObsAdqui(int cod_transaccion, java.lang.String obs_adqui) throws java.rmi.RemoteException;
    public java.util.HashMap[] setItemRegDesierto(java.lang.String tran, int cod_trans_detalle) throws java.rmi.RemoteException;
    public java.util.HashMap[] setActualizaTransaccionIngresoAlm(int cod_trans_nro, java.lang.String factura, java.lang.String fecha_fact, java.lang.String fecha_ing, java.lang.String memo, java.lang.String obs) throws java.rmi.RemoteException;
    public java.util.HashMap[] setActualizaTransaccionPpto(java.lang.String tran, int cod_transaccion, java.lang.String obs_ppto, java.lang.String hoja_ruta, java.lang.String cbte, java.lang.String certif_ppto, double monto_ppto, java.lang.String fondo) throws java.rmi.RemoteException;
    public java.util.HashMap[] setActualizaTransaccionAdq(java.lang.String tran, int cod_trans_nro, java.lang.String obs_adq, java.lang.String cod_proveedor, java.lang.String resolucion_adm, java.lang.String cuce, java.lang.String inf_comision, java.lang.String nro_propuesta) throws java.rmi.RemoteException;
    public java.util.HashMap[] addProveedor(int cod_trans_nro, java.lang.String cod_proveedor) throws java.rmi.RemoteException;
    public java.util.HashMap[] upProveedor(int cod_trans_nro, java.lang.String cod_proveedor) throws java.rmi.RemoteException;
    public java.util.HashMap[] downProveedor(int cod_trans_nro) throws java.rmi.RemoteException;
    public java.util.HashMap[] addObservacion(int cod_trans_nro, java.lang.String obs_adq) throws java.rmi.RemoteException;
    public java.util.HashMap[] addDatosOrdenCompra(int cod_trans_nro, java.lang.String resolucion_adm, java.lang.String cuce, java.lang.String inf_comision, java.lang.String nro_propuesta) throws java.rmi.RemoteException;
    public java.util.HashMap[] setAnulaTransaccionAdq(java.lang.String tran, int cod_transaccion) throws java.rmi.RemoteException;
    public java.util.HashMap[] setNuevoIngresoAlmacen(java.lang.String tran, int cod_tramite, int gestion, int cod_usuario, java.lang.String estado, java.lang.String ingreso_material) throws java.rmi.RemoteException;
    public java.util.HashMap[] addDetallex(java.lang.String tran, int cod_trans_detalle, java.lang.String detalle) throws java.rmi.RemoteException;
    public java.util.HashMap[] updateDetalle(java.lang.String tran, int cod_complemento, java.lang.String detalle) throws java.rmi.RemoteException;
    public java.lang.String getDetalleALM(java.lang.String tran, int cod_complemento) throws java.rmi.RemoteException;
    public java.util.HashMap[] addDetalleALM(java.lang.String tran, int cod_trans_detalle, java.lang.String detalle) throws java.rmi.RemoteException;
    public java.util.HashMap[] delDetalleALM(java.lang.String tran, int cod_complemento, int cod_trans_detalle) throws java.rmi.RemoteException;
    public java.util.HashMap[] updateDetalleALM(java.lang.String tran, int cod_complemento, java.lang.String detalle) throws java.rmi.RemoteException;
    public java.util.HashMap[] updateCantidadItem(java.lang.String tran, int cod_trans_detalle, int cantidad_pedido) throws java.rmi.RemoteException;
    public java.util.HashMap[] getReporteIngMaterialesAlmacen(java.lang.String fec_ini, java.lang.String fec_fin, int gestion) throws java.rmi.RemoteException;
    public java.util.HashMap[] getReporteDocsEnviados(java.lang.String fec_ini, java.lang.String fec_fin, int gestion) throws java.rmi.RemoteException;
    public java.util.HashMap[] getReporteAdjudicaciones(java.lang.String fec_ini, java.lang.String fec_fin, int gestion, int cod_cuantia) throws java.rmi.RemoteException;
    public java.util.HashMap[] getModalidad() throws java.rmi.RemoteException;
    public java.util.HashMap[] addProponente(java.lang.String cod_proveedor, int cod_transaccion, int cod_trans_nro, java.lang.String tipo, java.lang.String clase, java.lang.String nombre, java.lang.String nombre_comercial, java.lang.String direccion, java.lang.String telefono, java.lang.String adh_nombre) throws java.rmi.RemoteException;
    public java.util.HashMap[] delProponente(java.lang.String cod_proveedor, int cod_transaccion, int cod_trans_nro) throws java.rmi.RemoteException;
    public java.util.HashMap[] getProponentes(int cod_transaccion, int cod_trans_nro) throws java.rmi.RemoteException;
    public java.util.HashMap[] getProponenteADJ(int cod_trans_nro) throws java.rmi.RemoteException;
    public java.util.HashMap[] setProponenteADJ(int cod_trans_nro, java.lang.String cod_proveedor, java.lang.String nombre, java.lang.String nombre_comercial, java.lang.String direccion, java.lang.String telefono) throws java.rmi.RemoteException;
    public java.util.HashMap[] generaResIni(int cod_transaccion, int cod_tipo_resolucion, java.lang.String detalle, java.lang.String envia, java.lang.String detalle_nota_solicitud, java.lang.String detalle_nota_presupuesto, java.lang.String destino, int xx, int gestion) throws java.rmi.RemoteException;
    public java.util.HashMap[] getResIni(int cod_transaccion) throws java.rmi.RemoteException;
    public java.util.HashMap[] updateResIni(int cod_resolucion, java.lang.String envia, java.lang.String dns, java.lang.String dnp, java.lang.String destino, int dias) throws java.rmi.RemoteException;
    public java.util.HashMap[] generaResAdj(int cod_trans_nro, java.lang.String cod_proveedor, java.lang.String detalle) throws java.rmi.RemoteException;
    public java.util.HashMap[] getResAdj(int cod_trans_nro) throws java.rmi.RemoteException;
    public java.util.HashMap[] addResAdj(int cod_trans_nro, java.lang.String cod_proveedor, java.lang.String tipo, java.lang.String num_res_adm, java.lang.String notas_adq, java.lang.String num_adc_anpe, java.lang.String convocatoria, java.lang.String num_inf_adq, java.lang.String num_inf_hp, java.lang.String proveedor, java.lang.String destino, java.lang.String actividad, java.lang.String titulo) throws java.rmi.RemoteException;
    public java.util.HashMap[] gentabla(java.lang.String aaa, java.lang.String bbb, java.lang.String ccc, java.lang.String ddd, int xx, java.lang.String yy, java.lang.String f, java.lang.String g) throws java.rmi.RemoteException;
    public java.util.HashMap[] genResAdjServ2(int cod_trans_nro, int cod_tipo_resolucion, java.lang.String det_res_adj, java.lang.String det_res_adm, java.lang.String fecha_cc, java.lang.String det_inf_div_adq, java.lang.String det_conc_prop, java.lang.String modo_eval, java.lang.String destino, java.lang.String cargo, java.lang.String actividad, java.lang.String adc) throws java.rmi.RemoteException;
    public java.util.HashMap[] genResAdjBien(int cod_trans_nro, int cod_tipo_resolucion, java.lang.String det_res_adj, java.lang.String det_res_adm, java.lang.String fecha_cc, java.lang.String det_inf_div_adq, java.lang.String det_conc_prop, java.lang.String modo_eval, java.lang.String destino, java.lang.String cargo, java.lang.String actividad, java.lang.String adc) throws java.rmi.RemoteException;
    public java.util.HashMap[] genResAdjConsu(int cod_trans_nro, int cod_tipo_resolucion, java.lang.String det_res_adj, java.lang.String det_res_adm, java.lang.String fecha_cc, java.lang.String det_inf_div_adq, java.lang.String det_conc_prop, java.lang.String modo_eval, java.lang.String destino, java.lang.String cargo, java.lang.String actividad) throws java.rmi.RemoteException;
    public java.util.HashMap[] genResAdjObra(int cod_trans_nro, int cod_tipo_resolucion, java.lang.String det_res_adj, java.lang.String det_res_adm, java.lang.String fecha_cc, java.lang.String det_inf_div_adq, java.lang.String det_conc_prop, java.lang.String modo_eval, java.lang.String destino, java.lang.String cargo, java.lang.String actividad, java.lang.String tprov, java.lang.String tbche, java.lang.String adc) throws java.rmi.RemoteException;
    public java.util.HashMap[] getResAdjServ(int cod_trans_nro) throws java.rmi.RemoteException;
    public java.util.HashMap[] getResAdjBien(int cod_trans_nro) throws java.rmi.RemoteException;
    public java.util.HashMap[] getResAdjObra(int cod_trans_nro) throws java.rmi.RemoteException;
    public java.util.HashMap[] getResAdjConsul(int cod_trans_nro) throws java.rmi.RemoteException;
    public java.util.HashMap[] updateResAdjBien(int cod_trans_nro, int cod_tipo_resolucion, java.lang.String det_res_adm, java.lang.String fecha_cc, java.lang.String det_inf_div_adq, java.lang.String det_conc_prop, java.lang.String modo_eval, java.lang.String destino, java.lang.String cargo, java.lang.String actividad, java.lang.String adc) throws java.rmi.RemoteException;
    public java.util.HashMap[] updateResAdjObra(int cod_trans_nro, int cod_tipo_resolucion, java.lang.String det_res_adm, java.lang.String fecha_cc, java.lang.String det_inf_div_adq, java.lang.String det_conc_prop, java.lang.String modo_eval, java.lang.String destino, java.lang.String cargo, java.lang.String actividad, java.lang.String adc, java.lang.String a, java.lang.String b) throws java.rmi.RemoteException;
    public java.util.HashMap[] updateResAdjCons(int cod_trans_nro, int cod_tipo_resolucion, java.lang.String det_res_adm, java.lang.String fecha_cc, java.lang.String det_inf_div_adq, java.lang.String det_conc_prop, java.lang.String modo_eval, java.lang.String destino, java.lang.String cargo, java.lang.String actividad) throws java.rmi.RemoteException;
    public java.util.HashMap[] updateResAdjServ(java.lang.String adc, int cod_trans_nro, int cod_tipo_resolucion, java.lang.String det_res_adm, java.lang.String fecha_cc, java.lang.String det_inf_div_adq, java.lang.String det_conc_prop, java.lang.String modo_eval, java.lang.String destino, java.lang.String cargo, java.lang.String actividad) throws java.rmi.RemoteException;
    public java.util.HashMap[] updatetabla1(java.lang.String n1, java.lang.String n2, int cod_trans_nro) throws java.rmi.RemoteException;
    public java.util.HashMap[] setResAdj(int cod_trans_nro, java.lang.String num_res_adm, java.lang.String notas_adq, java.lang.String num_adc_anpe, java.lang.String convocatoria, java.lang.String num_inf_adq, java.lang.String num_inf_hp, java.lang.String proveedor, java.lang.String destino, java.lang.String actividad) throws java.rmi.RemoteException;
    public java.util.HashMap[] getTipoAdjuntos() throws java.rmi.RemoteException;
    public java.util.HashMap[] getConcursantes(int cod_transaccion) throws java.rmi.RemoteException;
    public java.util.HashMap[] existeReIni(int cod_transaccion) throws java.rmi.RemoteException;
    public java.util.HashMap[] insertDatosGenerales(java.lang.String codigo, java.lang.String descripcion) throws java.rmi.RemoteException;
    public java.util.HashMap[] getDatosGenerales() throws java.rmi.RemoteException;
    public java.util.HashMap[] getDatosGenerales2(int cod_almacen) throws java.rmi.RemoteException;
    public java.util.HashMap[] updateNombreRpa(java.lang.String cod_faculty, java.lang.String rpa) throws java.rmi.RemoteException;
    public java.util.HashMap[] updateRutaFirmaDigitalRPA(java.lang.String cod_faculty, java.lang.String firma_rpa) throws java.rmi.RemoteException;
    public java.util.HashMap[] updateRutaFirmaDigitalUSER(int cod_usuario, java.lang.String firma) throws java.rmi.RemoteException;
    public java.util.HashMap[] getDatosAlmacen(int cod_trans_nro) throws java.rmi.RemoteException;
    public java.lang.String getDatoGeneral(java.lang.String codigo) throws java.rmi.RemoteException;
    public java.util.HashMap[] updateDatosGenerales(java.lang.String codigo, java.lang.String descripcion) throws java.rmi.RemoteException;
    public java.util.HashMap[] getItemsPart(java.lang.String partida) throws java.rmi.RemoteException;
    public java.util.HashMap[] updateItemPPTO(java.lang.String cod_trans_detalle, java.lang.String cod_item, java.lang.String unidad_medida) throws java.rmi.RemoteException;
    public java.util.HashMap[] addItems(java.lang.String tran, int cod_item, int partida, java.lang.String articulo, java.lang.String unidad_medida, int gestion, java.lang.String estado, int cod_tipo_item) throws java.rmi.RemoteException;
    public java.lang.String getSEC_COD_ITEM() throws java.rmi.RemoteException;
    public java.util.HashMap[] getPartidas(java.lang.String gestion) throws java.rmi.RemoteException;
    public java.util.HashMap[] getPartidas1(int cod) throws java.rmi.RemoteException;
    public java.util.HashMap[] getdatosres15(int cod) throws java.rmi.RemoteException;
    public java.util.HashMap[] getresmay(int cod, int cod_t_n) throws java.rmi.RemoteException;
    public java.util.HashMap[] updateRes15(int cod, int cod_t_n, java.lang.String cite, java.lang.String destino, java.lang.String objetivo, java.lang.String cotizacion, java.lang.String doc, java.lang.String f, java.lang.String cargo) throws java.rmi.RemoteException;
    public java.util.HashMap[] generaRes15(int cod_trans, int cod_trans_nro, java.lang.String dias, java.lang.String cite, java.lang.String destino, java.lang.String objetivo, java.lang.String cotizacion, java.lang.String detalle, java.lang.String enviado, java.lang.String cargo, int gestion, java.lang.String doc, java.lang.String f) throws java.rmi.RemoteException;
    public java.util.HashMap[] getProgramaticApertGestion(int gestion, int cod_almacen) throws java.rmi.RemoteException;
    public java.util.HashMap[] getAlmacenGestion(int gestion) throws java.rmi.RemoteException;
    public java.lang.String getDescPartida(java.lang.String partida) throws java.rmi.RemoteException;
    public java.lang.String getCodFacultad(int cod_almacen) throws java.rmi.RemoteException;
    public java.util.HashMap[] getRepoAdquiOrden() throws java.rmi.RemoteException;
    public java.lang.String secTransDetComplemento() throws java.rmi.RemoteException;
    public java.lang.String secTransaccionDetalle() throws java.rmi.RemoteException;
    public java.lang.String secUnidadMedida() throws java.rmi.RemoteException;
    public java.util.HashMap[] addItem2(java.lang.String tran, int cod_transaccion, java.lang.String detalle, java.lang.String unidad_medida, int cantidad_pedido, int gestion) throws java.rmi.RemoteException;
    public java.util.HashMap[] updateItemx(java.lang.String tran, java.lang.String cod_trans_detalle, java.lang.String detalle, int cod_unidad_medida, int cantidad_pedido, java.lang.String partida) throws java.rmi.RemoteException;
    public java.util.HashMap[] updateItem(java.lang.String tran, java.lang.String cod_trans_detalle, java.lang.String detalle, int cod_unidad_medida, int cantidad_pedido) throws java.rmi.RemoteException;
    public java.util.HashMap[] delDetallex(java.lang.String tran, int cod_complemento) throws java.rmi.RemoteException;
    public java.util.HashMap[] getItemClasificador(int gestion, int partida) throws java.rmi.RemoteException;
    public java.util.HashMap[] updateCodItem(java.lang.String tran, int cod_trans_detalle, int cod_item) throws java.rmi.RemoteException;
    public java.util.HashMap[] delComplemento(java.lang.String tran, int cod_trans_detalle) throws java.rmi.RemoteException;
    public java.util.HashMap[] delDetalleNro(java.lang.String tran, int cod_trans_detalle) throws java.rmi.RemoteException;
    public java.util.HashMap[] delItemRefFecha(java.lang.String tran, int cod_trans_detalle) throws java.rmi.RemoteException;
    public java.util.HashMap[] delItemx(java.lang.String tran, int cod_trans_detalle) throws java.rmi.RemoteException;
    public java.util.HashMap[] addPreventivo(java.lang.String tran, int cod_transaccion, java.lang.String cod_preventivo, java.lang.String resumen, int da, java.lang.String total) throws java.rmi.RemoteException;
    public java.util.HashMap[] getPreventivos(int cod_transaccion) throws java.rmi.RemoteException;
    public java.util.HashMap[] delPreventivo(java.lang.String tran, int cod_transaccion, java.lang.String cod_preventivo) throws java.rmi.RemoteException;
    public java.util.HashMap[] getTotalPartidas(int cod_trans_nro) throws java.rmi.RemoteException;
    public java.util.HashMap[] getFechasRestriccion(int cod_transaccion) throws java.rmi.RemoteException;
    public java.util.HashMap[] getFechasRestriccionAdquiDepto() throws java.rmi.RemoteException;
    public java.util.HashMap[] setCodW(java.lang.String tran, int cod_transaccion, int cod_w) throws java.rmi.RemoteException;
    public java.util.HashMap[] addFechaRestriccion(java.lang.String tran, int cod_tipo_resf, int cod_trans_nro, java.lang.String fecha_conclusion, java.lang.String lugar) throws java.rmi.RemoteException;
    public java.util.HashMap[] addFechaRestriccion3(java.lang.String tran, int cod_tipo_resf, int cod_trans_nro, java.lang.String fecha_conclusion, java.lang.String lugar, java.lang.String hora_inicio) throws java.rmi.RemoteException;
    public java.util.HashMap[] addFechaBoletaGarantia(java.lang.String tran, int cod_tipo_resf, int cod_trans_nro, java.lang.String fecha_inicio, java.lang.String fecha_conclusion) throws java.rmi.RemoteException;
    public java.util.HashMap[] addFechaRestriccion2(java.lang.String tran, int cod_tipo_resf, int cod_trans_nro, java.lang.String fecha_inicio, java.lang.String fecha_conclusion, java.lang.String lugar, java.lang.String hora_inicio) throws java.rmi.RemoteException;
    public java.util.HashMap[] updateFechaEntrega(java.lang.String tran, int cod_tipo_resf, int cod_trans_nro, java.lang.String fecha_inicio, java.lang.String fecha_conclusion) throws java.rmi.RemoteException;
    public java.util.HashMap[] getRestriccionFechas(int cod_trans_nro, int cod_tipo_resf) throws java.rmi.RemoteException;
    public java.util.HashMap[] getRestriccionFechas(int cod_trans_nro) throws java.rmi.RemoteException;
    public java.util.HashMap[] getCod_Trans(int cod_transaccion) throws java.rmi.RemoteException;
    public java.util.HashMap[] fechasExtra(java.lang.String a, java.lang.String b, int c, int d) throws java.rmi.RemoteException;
    public java.util.HashMap[] dias_restantes(int cod_trans_nro) throws java.rmi.RemoteException;
    public java.util.HashMap[] notificacionfechas() throws java.rmi.RemoteException;
    public java.util.HashMap[] addContrato(java.lang.String tran, int cod_trans_nro, java.lang.String a, java.lang.String b, java.lang.String c, java.lang.String d, java.lang.String e, java.lang.String f, java.lang.String g, java.lang.String h, java.lang.String i, java.lang.String j, java.lang.String k, java.lang.String l, java.lang.String m, java.lang.String n, java.lang.String o, java.lang.String p, java.lang.String q, java.lang.String r, java.lang.String s, java.lang.String t, java.lang.String u, java.lang.String v, java.lang.String w, java.lang.String x, java.lang.String y, java.lang.String z, java.lang.String a1, java.lang.String b1) throws java.rmi.RemoteException;
    public java.util.HashMap[] addContrato(java.lang.String tran, int cod_trans_nro, java.lang.String a, java.lang.String b, java.lang.String c, java.lang.String d, java.lang.String e, java.lang.String f, java.lang.String g, java.lang.String h, java.lang.String i, java.lang.String j, java.lang.String k, java.lang.String l, java.lang.String m, java.lang.String n, java.lang.String o, java.lang.String p, java.lang.String q, java.lang.String r, java.lang.String s, java.lang.String t, java.lang.String u, java.lang.String v, java.lang.String w, java.lang.String x, java.lang.String y, java.lang.String z) throws java.rmi.RemoteException;
    public java.util.HashMap[] updateContrato(java.lang.String tran, int cod_trans_nro, java.lang.String a, java.lang.String b, java.lang.String c, java.lang.String d, java.lang.String e, java.lang.String f, java.lang.String g, java.lang.String h, java.lang.String i, java.lang.String j, java.lang.String k, java.lang.String l, java.lang.String m, java.lang.String n, java.lang.String o, java.lang.String p, java.lang.String q, java.lang.String r, java.lang.String s, java.lang.String t, java.lang.String u, java.lang.String v, java.lang.String w, java.lang.String x, java.lang.String y, java.lang.String z, java.lang.String a1, java.lang.String b1) throws java.rmi.RemoteException;
    public java.util.HashMap[] getContrato(int cod_trans_nro) throws java.rmi.RemoteException;
    public java.util.HashMap[] getAdjunto(int cod_transaccion, int cod_adjunto) throws java.rmi.RemoteException;
    public java.util.HashMap[] addCuceSicoes(java.lang.String tran, int cod_transaccion, java.lang.String cuce_sicoes) throws java.rmi.RemoteException;
    public java.util.HashMap[] getCuceSicoes(int cod_transaccion) throws java.rmi.RemoteException;
    public java.util.HashMap[] addAdmAlm(java.lang.String tran, int cod_usuario, int cod_almacen, int gestion) throws java.rmi.RemoteException;
    public java.util.HashMap[] updateAdmAlm(java.lang.String tran, int cod_usr_alm, int cod_usuario, int cod_almacen) throws java.rmi.RemoteException;
    public java.util.HashMap[] getNotaConformidad(int cod_trans_nro) throws java.rmi.RemoteException;
    public java.util.HashMap[] updateNotaConformidad(java.lang.String tran, int cod_trans_nro, java.lang.String fecha_nc, java.lang.String hora_nc, java.lang.String ciudad, java.lang.String lugar) throws java.rmi.RemoteException;
    public java.util.HashMap[] addHojaRuta(java.lang.String tran, int cod_transaccion, java.lang.String hoja_ruta) throws java.rmi.RemoteException;
    public java.lang.String getHojaRuta(int cod_transaccion) throws java.rmi.RemoteException;
    public java.util.HashMap[] getProveedoresbusca(java.lang.String a, java.lang.String b, java.lang.String c) throws java.rmi.RemoteException;
    public java.util.HashMap[] getFirmaUsuario(int cod_trans_nro) throws java.rmi.RemoteException;
    public java.util.HashMap[] getFirmaUsuario2(int cod_transaccion) throws java.rmi.RemoteException;
    public java.util.HashMap[] getItem(java.lang.String cod_item) throws java.rmi.RemoteException;
    public java.util.HashMap[] addItem(java.lang.String tran, int cod_trans_detalle, int cod_transaccion, int gestion) throws java.rmi.RemoteException;
    public java.util.HashMap[] getTotal(int cod_trans_nro) throws java.rmi.RemoteException;
    public java.util.HashMap[] getItems() throws java.rmi.RemoteException;
    public java.util.HashMap[] getItems(int cod_transaccion) throws java.rmi.RemoteException;
}
