/*
 * DiagRoles.java
 *
 * Created on 14 de octubre de 2008, 14:56
 */

package umsa.capricornio.gui.menu;

import umsa.capricornio.domain.Roles;


/**
 *
 * @author  julian
 */
public class DiagRoles extends javax.swing.JDialog {

    FrmMenu menu;
            
    String[][] roles;
    private Runtime r;
    private int cod_rol;
    /** Creates new form DiagRoles */
    public DiagRoles(FrmMenu menu,String[][] roles) {
        super(menu, true);
        initComponents();
        this.menu=menu;
        this.roles=roles;
    }
    
    public boolean AbreRoles(){
        setVisible(true);
        return true;
    }
    
    public Roles RolElegido(){
        Roles rol = new Roles();
        rol.setCod_rol(cod_rol);
        rol.setRol(CmbRoles.getSelectedItem().toString());
        return rol;
    }
    
    private void LLenaRoles(){                
       String rol="";        
       for (int c=0;c<roles.length;c++){                        
            CmbRoles.addItem(roles[c][1]);
        }               
    }
        
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CmbRoles = new javax.swing.JComboBox();
        BtnAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        CmbRoles.setFont(new java.awt.Font("Arial", 1, 12));
        CmbRoles.setForeground(new java.awt.Color(0, 51, 153));
        CmbRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbRolesActionPerformed(evt);
            }
        });
        getContentPane().add(CmbRoles);
        CmbRoles.setBounds(40, 20, 360, 23);

        BtnAceptar.setFont(new java.awt.Font("Arial", 1, 12));
        BtnAceptar.setForeground(new java.awt.Color(0, 51, 153));
        BtnAceptar.setText("Aceptar");
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAceptar);
        BtnAceptar.setBounds(160, 60, 100, 25);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Rol");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 20, 20);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-437)/2, (screenSize.height-136)/2, 437, 136);
    }// </editor-fold>//GEN-END:initComponents

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      LLenaRoles();
}//GEN-LAST:event_formWindowOpened

private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
    System.gc();
    r = Runtime.getRuntime();
    long mem1 = r.freeMemory();
    dispose();
}//GEN-LAST:event_BtnAceptarActionPerformed

private void CmbRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbRolesActionPerformed
    for (int f=0;f<roles.length;f++)
        if (roles[f][1].equals(CmbRoles.getSelectedItem()))
            cod_rol=Integer.parseInt(roles[f][0]);
}//GEN-LAST:event_CmbRolesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JComboBox CmbRoles;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
