/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package umsa.capricornio.gui.Maestros;

import java.rmi.RemoteException;
import java.util.Map;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.xml.rpc.ServiceException;
import umsa.capricornio.gui.ConnectADQUI.AdquiWSServiceLocator;
import umsa.capricornio.gui.ConnectADQUI.AdquiWS_PortType;
import umsa.capricornio.gui.Maestros.tablas.TablaAlmacen;
import umsa.capricornio.gui.menu.FrmMenu;

/**
 *
 * @author julian
 */
public class FrmAlmacenes extends javax.swing.JInternalFrame {
    TablaAlmacen almacen;
    FrmMenu menu;
    int gestion;
    private Runtime r;
    /**
     * Creates new form FrmAlmacenes
     */
    public FrmAlmacenes(FrmMenu menu, int gestion) {
        //this.menu=menu;
        this.menu=menu;
        this.gestion=gestion;
        initComponents();        
        ConstruyeTablaUsuarios();
       
    }

    private void ConstruyeTablaUsuarios(){        
        almacen = new TablaAlmacen();        
        TblAlmacen.setAutoCreateColumnsFromModel(false);
        TblAlmacen.setModel(almacen); 
        
        for (int k = 0; k < TablaAlmacen.m_columns.length; k++) {               
            DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
            renderer.setHorizontalAlignment(TablaAlmacen.m_columns[k].m_alignment);
            TableColumn column = new TableColumn(k, TablaAlmacen.m_columns[k].m_width, renderer, null);
            TblAlmacen.addColumn(column);
        }        
        JTableHeader header = TblAlmacen.getTableHeader();
        header.setUpdateTableInRealTime(true);
        header.setReorderingAllowed(true);

        PnlAlmacen.getViewport().add(TblAlmacen);        
        //getContentPane().add(PnlTechos, BorderLayout.CENTER);
    }
        
    private void LlenaAlmacen(){
        CerearTablaAlmacen();    
        try{
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            Map[] datos= puerto.getAlmacen(gestion);
            if (datos!=null){
                for (int c=0;c<datos.length;c++){
                    almacen.insert(c);                    
                    TblAlmacen.tableChanged(new TableModelEvent(almacen, c, c, TableModelEvent.ALL_COLUMNS,TableModelEvent.INSERT)); 
                    TblAlmacen.setValueAt(datos[c].get("COD_ALMACEN"),c,0);
                    TblAlmacen.setValueAt(datos[c].get("ALMACEN"),c,1);
                    TblAlmacen.setValueAt(datos[c].get("FACULTAD"),c,2);
                    TblAlmacen.setValueAt(datos[c].get("COD_FAC"),c,3);
                }                
            }                    
        }
        catch (RemoteException e){ 
            javax.swing.JOptionPane.showMessageDialog(this,"<html> error de conexion con el servidor <br> "+e,"ZODIAC LIBRA SYSTEM",
                        javax.swing.JOptionPane.ERROR_MESSAGE);           
        }
        catch (ServiceException e){ System.out.println(e);}        
    }
    
    void CerearTablaAlmacen(){
        int f = TblAlmacen.getRowCount();
        for (int i=f;i>=0;i--){
             if (almacen.delete(i)) {
                TblAlmacen.tableChanged(new TableModelEvent(
                almacen, i, i, TableModelEvent.ALL_COLUMNS, TableModelEvent.INSERT)); 
             }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlAlmacen = new javax.swing.JScrollPane();
        TblAlmacen = new javax.swing.JTable();
        BtnNuevo = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        TxtDescripcion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TxtDA = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtCodDA = new javax.swing.JTextField();

        setTitle("ALMACENES");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        TblAlmacen.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TblAlmacen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblAlmacenMouseClicked(evt);
            }
        });
        PnlAlmacen.setViewportView(TblAlmacen);

        getContentPane().add(PnlAlmacen);
        PnlAlmacen.setBounds(10, 10, 490, 170);

        BtnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umsa/capricornio/gui/images/page.png"))); // NOI18N
        BtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnNuevo);
        BtnNuevo.setBounds(120, 300, 30, 25);

        BtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umsa/capricornio/gui/images/disk_multiple.png"))); // NOI18N
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnGuardar);
        BtnGuardar.setBounds(150, 300, 30, 25);

        BtnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umsa/capricornio/gui/images/page_edit.png"))); // NOI18N
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnModificar);
        BtnModificar.setBounds(180, 300, 30, 25);

        BtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umsa/capricornio/gui/images/eliminar.gif"))); // NOI18N
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnEliminar);
        BtnEliminar.setBounds(210, 300, 30, 25);

        BtnSalir.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        BtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umsa/capricornio/gui/images/arrow_left.png"))); // NOI18N
        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSalir);
        BtnSalir.setBounds(300, 300, 90, 25);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Adminsitracion de Almacenes"));
        jPanel1.setLayout(null);

        TxtDescripcion.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jPanel1.add(TxtDescripcion);
        TxtDescripcion.setBounds(110, 30, 360, 20);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setText("Descrip. almacen :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 30, 90, 20);

        TxtDA.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jPanel1.add(TxtDA);
        TxtDA.setBounds(110, 60, 220, 20);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("D. A. :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 60, 80, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel3.setText("Cod. D.A. :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(360, 60, 60, 20);

        TxtCodDA.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jPanel1.add(TxtCodDA);
        TxtCodDA.setBounds(430, 60, 40, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 190, 490, 100);

        setBounds(0, 0, 527, 367);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        if ("".equals(TxtDescripcion.getText().trim()) ) {
            javax.swing.JOptionPane.showMessageDialog(this,"Debe introducir el nombre del almacen","ZODIAC CAPRICORN SYSTEM",
            javax.swing.JOptionPane.ERROR_MESSAGE);
            TxtDescripcion.requestFocus();
            return;
        }
        if ("".equals(TxtDA.getText().trim()) ) {
            javax.swing.JOptionPane.showMessageDialog(this,"Debe introducir la Direccion Administrativa","ZODIAC CAPRICORN SYSTEM",
            javax.swing.JOptionPane.ERROR_MESSAGE);
            TxtDA.requestFocus();
            return;
        }
        if ("".equals(TxtCodDA.getText().trim()) ) {
            javax.swing.JOptionPane.showMessageDialog(this,"Debe introducir el codigo de la Direccion Administrativa","ZODIAC CAPRICORN SYSTEM",
            javax.swing.JOptionPane.ERROR_MESSAGE);
            TxtCodDA.requestFocus();
            return;
        }        
        int res = javax.swing.JOptionPane.showConfirmDialog( this,"¿Desea guardar los datos?",
                "ZODIAC LIBRA SYSTEM",javax.swing.JOptionPane.YES_NO_OPTION );
        if (res == javax.swing.JOptionPane.NO_OPTION) return;
        try {   AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
                AdquiWS_PortType puerto = servicio.getAdquiWS();
                Map[] datos = datos=puerto.setAlmacen("SET-insDataAlm",TxtDescripcion.getText().trim(),TxtDA.getText().trim(),TxtCodDA.getText().trim(),gestion);
                javax.swing.JOptionPane.showMessageDialog(this,"Usuario Registrado","ZODIAC CAPRICORN SYSTEM",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
                LlenaAlmacen();
                TxtDescripcion.setText("");
                TxtDA.setText("");
                TxtCodDA.setText("");                
                TxtDescripcion.requestFocus();            
            } catch (RemoteException ex) {
                javax.swing.JOptionPane.showMessageDialog(this,"<html> error de conexion con el servidor <br> "+ex,"ZODIAC LIBRA SYSTEM",
                                javax.swing.JOptionPane.ERROR_MESSAGE);    } 
            catch (ServiceException ex) {}
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        if ("".equals(TxtDescripcion.getText().trim()) ) {
            javax.swing.JOptionPane.showMessageDialog(this,"Debe introducir el nombre del almacen","ZODIAC CAPRICORN SYSTEM",
            javax.swing.JOptionPane.ERROR_MESSAGE);
            TxtDescripcion.requestFocus();
            return;
        }
        if ("".equals(TxtDA.getText().trim()) ) {
            javax.swing.JOptionPane.showMessageDialog(this,"Debe introducir la Direccion Administrativa","ZODIAC CAPRICORN SYSTEM",
            javax.swing.JOptionPane.ERROR_MESSAGE);
            TxtDA.requestFocus();
            return;
        }
        if ("".equals(TxtCodDA.getText().trim()) ) {
            javax.swing.JOptionPane.showMessageDialog(this,"Debe introducir el codigo de la Direccion Administrativa","ZODIAC CAPRICORN SYSTEM",
            javax.swing.JOptionPane.ERROR_MESSAGE);
            TxtCodDA.requestFocus();
            return;
        }        
        int res = javax.swing.JOptionPane.showConfirmDialog( this,"¿Desea modificar los datos?",
                "ZODIAC LIBRA SYSTEM",javax.swing.JOptionPane.YES_NO_OPTION );
        if (res == javax.swing.JOptionPane.NO_OPTION) return;
        int f = TblAlmacen.getSelectedRow();
        int cod_almacen=Integer.parseInt(TblAlmacen.getValueAt(f, 0).toString());
        
        try {   AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
                AdquiWS_PortType puerto = servicio.getAdquiWS();
                Map[] datos = datos=puerto.setAlmacenModif("SET-updDataAlm",cod_almacen,TxtDescripcion.getText().trim(),TxtDA.getText().trim(),TxtCodDA.getText().trim(),gestion);
                javax.swing.JOptionPane.showMessageDialog(this,"Datos Modificados","ZODIAC CAPRICORN SYSTEM",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
                LlenaAlmacen();
                BtnEliminar.setEnabled(false);
                BtnModificar.setEnabled(false);
                BtnGuardar.setEnabled(true);
                TblAlmacen.setEnabled(true);
                TxtDescripcion.setText("");
                TxtDA.setText("");
                TxtCodDA.setText("");                
                TxtDescripcion.requestFocus();            
            } catch (RemoteException ex) {
                javax.swing.JOptionPane.showMessageDialog(this,"<html> error de conexion con el servidor <br> "+ex,"ZODIAC LIBRA SYSTEM",
                                javax.swing.JOptionPane.ERROR_MESSAGE);    } 
            catch (ServiceException ex) {}
    }//GEN-LAST:event_BtnModificarActionPerformed

    private void BtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevoActionPerformed
        BtnEliminar.setEnabled(false);
        BtnModificar.setEnabled(false);
        BtnGuardar.setEnabled(true); 
        TblAlmacen.setEnabled(true);
        TxtDescripcion.requestFocus();
    }//GEN-LAST:event_BtnNuevoActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        int res = javax.swing.JOptionPane.showConfirmDialog( this,"¿Desea Eliminar los datos?",
                "ZODIAC LIBRA SYSTEM",javax.swing.JOptionPane.YES_NO_OPTION );
        if (res == javax.swing.JOptionPane.NO_OPTION) return;
        int f = TblAlmacen.getSelectedRow();
        int cod_almacen=Integer.parseInt(TblAlmacen.getValueAt(f, 0).toString());
        
        try {   AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
                AdquiWS_PortType puerto = servicio.getAdquiWS();
                Map[] datos = datos=puerto.setAlmacenDel("SET-delDataAlm",cod_almacen,gestion);
                javax.swing.JOptionPane.showMessageDialog(this,"Datos Eliminados","ZODIAC CAPRICORN SYSTEM",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
                LlenaAlmacen();
                BtnEliminar.setEnabled(false);
                BtnModificar.setEnabled(false);
                BtnGuardar.setEnabled(true); 
                TblAlmacen.setEnabled(true);
                TxtDescripcion.setText("");
                TxtDA.setText("");
                TxtCodDA.setText("");                
                TxtDescripcion.requestFocus();            
            } 
        catch (RemoteException ex) {
                javax.swing.JOptionPane.showMessageDialog(this,"<html> error de conexion con el servidor <br> "+ex,"ZODIAC LIBRA SYSTEM",
                                javax.swing.JOptionPane.ERROR_MESSAGE);    } 
        catch (ServiceException ex) {}
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        BtnGuardar.setEnabled(true);
        BtnModificar.setEnabled(false);
        BtnEliminar.setEnabled(false);
        LlenaAlmacen();
    }//GEN-LAST:event_formInternalFrameOpened

    private void TblAlmacenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblAlmacenMouseClicked
        if (evt.getClickCount() == 2) {            
            BtnEliminar.setEnabled(true);
            BtnModificar.setEnabled(true);
            BtnGuardar.setEnabled(false);
            TblAlmacen.setEnabled(false);
            int fila=TblAlmacen.getSelectedRow();        
            TxtDescripcion.setText(TblAlmacen.getValueAt(fila,1).toString());
            TxtDA.setText(TblAlmacen.getValueAt(fila,2).toString()); 
            TxtCodDA.setText(TblAlmacen.getValueAt(fila,3).toString());  
        }
    }//GEN-LAST:event_TblAlmacenMouseClicked

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        menu.CerrarFrameInterno(this);
        System.gc();
        r = Runtime.getRuntime();
        long mem1 = r.freeMemory();
    }//GEN-LAST:event_BtnSalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JButton BtnNuevo;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JScrollPane PnlAlmacen;
    private javax.swing.JTable TblAlmacen;
    private javax.swing.JTextField TxtCodDA;
    private javax.swing.JTextField TxtDA;
    private javax.swing.JTextField TxtDescripcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
