/*
 * FrmIndicadores.java
 *
 * Created on 24 de julio de 2008, 9:21
 */

package umsa.capricornio.gui.Maestros;

import java.awt.event.KeyEvent;
import java.rmi.RemoteException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.xml.rpc.ServiceException;
import umsa.capricornio.gui.ConnectADQUI.AdquiWSServiceLocator;
import umsa.capricornio.gui.ConnectADQUI.AdquiWS_PortType;
import umsa.capricornio.gui.Maestros.tablas.TablaFechas;
import umsa.capricornio.gui.Maestros.tablas.TablaGestion;
import umsa.capricornio.gui.menu.FrmMenu;
import umsa.capricornio.utilitarios.herramientas.validacion;

/**
 *
 * @author  julian
 */
public class FrmFechasNH extends javax.swing.JInternalFrame {
    
    TablaFechas fechas;    
        
    Runtime r;
    FrmMenu menu;
    private int fila;
    
    /** Creates new form FrmIndicadores */
    public FrmFechasNH(FrmMenu menu) {
        this.menu=menu;
        initComponents();
        ConstruyeTablaGestion();
    }

    private void ConstruyeTablaGestion(){        
        fechas = new TablaFechas();        
        TblFechas.setAutoCreateColumnsFromModel(false);
        TblFechas.setModel(fechas); 
        
        for (int k = 0; k < TablaGestion.m_columns.length; k++) {               
            DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
            renderer.setHorizontalAlignment(TablaGestion.m_columns[k].m_alignment);
            TableColumn column = new TableColumn(k, TablaGestion.m_columns[k].m_width, renderer, null);
            TblFechas.addColumn(column);                           
        }        
        JTableHeader header = TblFechas.getTableHeader();
        header.setUpdateTableInRealTime(true);
        header.setReorderingAllowed(true);

        PnlGestion.getViewport().add(TblFechas);        
        //getContentPane().add(PnlTechos, BorderLayout.CENTER);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlGestion = new javax.swing.JScrollPane();
        TblFechas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        BtnNuevo = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        DatFec_ini = new net.sf.nachocalendar.components.DateField();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        PnlGestion.setBorder(javax.swing.BorderFactory.createTitledBorder("Fechas No Habiles"));

        TblFechas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TblFechas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TblFechasMousePressed(evt);
            }
        });
        PnlGestion.setViewportView(TblFechas);

        getContentPane().add(PnlGestion);
        PnlGestion.setBounds(0, 0, 220, 180);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Administracion de Usuarios"));
        jPanel1.setLayout(null);

        BtnNuevo.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        BtnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umsa/capricornio/gui/images/page.png"))); // NOI18N
        BtnNuevo.setToolTipText("Nuevo");
        BtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(BtnNuevo);
        BtnNuevo.setBounds(10, 50, 30, 25);

        BtnGuardar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        BtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umsa/capricornio/gui/images/disk_multiple.png"))); // NOI18N
        BtnGuardar.setToolTipText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnGuardar);
        BtnGuardar.setBounds(40, 50, 30, 25);

        BtnModificar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        BtnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umsa/capricornio/gui/images/page_edit.png"))); // NOI18N
        BtnModificar.setToolTipText("Modificar");
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnModificar);
        BtnModificar.setBounds(70, 50, 30, 25);

        BtnEliminar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        BtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umsa/capricornio/gui/images/eliminar.gif"))); // NOI18N
        BtnEliminar.setToolTipText("Eliminar");
        BtnEliminar.setEnabled(false);
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnEliminar);
        BtnEliminar.setBounds(100, 50, 30, 25);

        jButton5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umsa/capricornio/gui/images/arrow_left.png"))); // NOI18N
        jButton5.setMnemonic('S');
        jButton5.setText("Salir");
        jButton5.setToolTipText("Salir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(130, 50, 80, 25);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Fechas no Habiles");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 20, 100, 20);

        DatFec_ini.setDateFormat(DateFormat.getDateInstance(DateFormat.MEDIUM));
        jPanel1.add(DatFec_ini);
        DatFec_ini.setBounds(120, 20, 90, 18);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 190, 220, 90);

        setBounds(0, 0, 240, 315);
    }// </editor-fold>//GEN-END:initComponents

private void BtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevoActionPerformed
    BtnEliminar.setEnabled(false);
    BtnModificar.setEnabled(false);
    BtnGuardar.setEnabled(true); 
    TblFechas.setEnabled(true);
    /*TxtGestion.setText("");    
    TxtGestion.requestFocus(); */
}//GEN-LAST:event_BtnNuevoActionPerformed

private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
     /*if ("".equals(DatFec_ini.getValue()) || !(validacion.valNumero(DatFec_ini.getValue().toString, 4, 4))) {
        javax.swing.JOptionPane.showMessageDialog(this,"Debe introducir datos numericos","SYSTEM CAPRICORN SYSTEM",
        javax.swing.JOptionPane.ERROR_MESSAGE);  
        TxtGestion.requestFocus();        
        return;
    }*/
    
    int res = javax.swing.JOptionPane.showConfirmDialog( this,"¿Desea guardar los datos?",
                "Traspasos Presupuestarios",javax.swing.JOptionPane.YES_NO_OPTION );
    if (res == javax.swing.JOptionPane.NO_OPTION) return;
    try {   AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            DateFormat df2 = DateFormat.getDateInstance(DateFormat.MEDIUM);
            String s1 = df2.format(this.DatFec_ini.getValue());
            System.out.println("lo que ingresa "+s1);
            Map[] datos = datos=puerto.setFechasNH(s1);                
            javax.swing.JOptionPane.showMessageDialog(this,"Gestion registrada","SYSTEM CAPRICORN SYSTEM",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);              
            LlenaGestion();                          
            /*TxtGestion.setText("");                    
            TxtGestion.requestFocus();*/
        } catch (RemoteException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,"<html> error de conexion con el servidor <br> "+ex,"SYSTEM CAPRICORN SYSTEM",
                            javax.swing.JOptionPane.ERROR_MESSAGE);    } 
        catch (ServiceException ex) {}
}//GEN-LAST:event_BtnGuardarActionPerformed

void CerearTablaGestion(){
        int f = TblFechas.getRowCount();
        for (int i=f;i>=0;i--){
             if (fechas.delete(i)) {
                TblFechas.tableChanged(new TableModelEvent(
                fechas, i, i, TableModelEvent.ALL_COLUMNS, TableModelEvent.INSERT)); 
             }
        }
    }

private void LlenaGestion(){
    CerearTablaGestion();    
        try{
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();             
            Map[] datos= puerto.getFechasNH();
            if (datos!=null){
                for (int c=0;c<datos.length;c++){
                    System.out.println("entro ya es algo");
                    fechas.insert(c);
                    System.out.println("entro ya es algo");
                    TblFechas.tableChanged(new TableModelEvent(fechas, c, c, TableModelEvent.ALL_COLUMNS,TableModelEvent.INSERT)); 
                    System.out.println("el cod "+datos[c].get("COD"));
                    TblFechas.setValueAt(datos[c].get("COD"),c,0);
                    System.out.println("el cod "+datos[c].get("FECHAS"));
                    TblFechas.setValueAt(datos[c].get("FECHAS"),c,1);                    
                }                
            }
            else
                System.out.println("noooooo");
        }
        catch (RemoteException e){ 
            javax.swing.JOptionPane.showMessageDialog(this,"<html> error de conexion con el servidor <br> "+e,"SYSTEM CAPRICORN SYSTEM",
                        javax.swing.JOptionPane.ERROR_MESSAGE);           
        }
        catch (ServiceException e){ System.out.println(e);}        
    }

private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
    int res = javax.swing.JOptionPane.showConfirmDialog( this,"¿Desea Modificar esta Gestion?",
                "SYSTEM CAPRICORN SYSTEM",javax.swing.JOptionPane.YES_NO_OPTION );
    if (res == javax.swing.JOptionPane.NO_OPTION) return;
    
    int f = TblFechas.getSelectedRow();
    int cod_gestion=Integer.parseInt(TblFechas.getValueAt(f, 0).toString());
    try {   AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            DateFormat df2 = DateFormat.getDateInstance();
            String s1 = df2.format(this.DatFec_ini.getValue());
            System.out.println("lo que ingresa "+s1+" y el codigo"+cod_gestion);
            Map[] datos = puerto.setFechasModif(cod_gestion,s1);            
            javax.swing.JOptionPane.showMessageDialog(this,"Datos modificados","SYSTEM CAPRICORN SYSTEM",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);                      
            LlenaGestion();                
            BtnEliminar.setEnabled(false);
            BtnModificar.setEnabled(false);
            BtnGuardar.setEnabled(true);  
            TblFechas.setEnabled(true);
            /*TxtGestion.setText("");
            TxtGestion.requestFocus();*/
    } catch (RemoteException ex) {
        javax.swing.JOptionPane.showMessageDialog(this,"<html> error de conexion con el servidor <br> "+ex,"SYSTEM CAPRICORN SYSTEM",
                        javax.swing.JOptionPane.ERROR_MESSAGE);    } 
    catch (ServiceException ex) {}
}//GEN-LAST:event_BtnModificarActionPerformed

private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
  // 
    int res = javax.swing.JOptionPane.showConfirmDialog( this,"¿Desea Eliminar esta Fecha?",
                "SYSTEM CAPRICORN SYSTEM",javax.swing.JOptionPane.YES_NO_OPTION );
    if (res == javax.swing.JOptionPane.NO_OPTION) return;
    
    int f = TblFechas.getSelectedRow();
    int cod_gestion=Integer.parseInt(TblFechas.getValueAt(f, 0).toString());
    try {   AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            DateFormat df2 = DateFormat.getDateInstance(DateFormat.MEDIUM);
            String s1 = df2.format(this.DatFec_ini.getValue());
            System.out.println("lo que ingresa "+s1+" y el codigo"+cod_gestion);
            Map[] datos = puerto.eliminaFecha(cod_gestion);            
            javax.swing.JOptionPane.showMessageDialog(this,"Datos modificados","SYSTEM CAPRICORN SYSTEM",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);                      
            LlenaGestion();                
            BtnEliminar.setEnabled(false);
            BtnModificar.setEnabled(false);
            BtnGuardar.setEnabled(true);  
            TblFechas.setEnabled(true);
            /*TxtGestion.setText("");
            TxtGestion.requestFocus();*/
    } catch (RemoteException ex) {
        javax.swing.JOptionPane.showMessageDialog(this,"<html> error de conexion con el servidor <br> "+ex,"SYSTEM CAPRICORN SYSTEM",
                        javax.swing.JOptionPane.ERROR_MESSAGE);    } 
    catch (ServiceException ex) {}
}//GEN-LAST:event_BtnEliminarActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    menu.CerrarFrameInterno(this);
    System.gc();
    r = Runtime.getRuntime();
    long mem1 = r.freeMemory();
}//GEN-LAST:event_jButton5ActionPerformed
    
private void TblFechasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblFechasMousePressed
    if (evt.getClickCount() == 2) {        
        BtnModificar.setEnabled(true);
        BtnEliminar.setEnabled(true);
        BtnNuevo.setEnabled(false);
        BtnGuardar.setEnabled(false);
        TblFechas.setEnabled(false);
        fila=TblFechas.getSelectedRow();
        String x=TblFechas.getValueAt(fila,1).toString();
        System.out.println("aqui esta el numero "+x);
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        Date f=null;
        try {
            f = formatter.parse(x);
            System.out.println("si entro ");
        } catch (ParseException ex) {
            Logger.getLogger(FrmFechasNH.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("aqui esta el numero "+f);
        DatFec_ini.setValue(f);
        //TxtGestion.setText(TblFechas.getValueAt(fila,1).toString()); 
    }
}//GEN-LAST:event_TblFechasMousePressed

private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
    LlenaGestion();
    BtnGuardar.setEnabled(true);
    BtnModificar.setEnabled(false);
    BtnEliminar.setEnabled(false);
}//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JButton BtnNuevo;
    private net.sf.nachocalendar.components.DateField DatFec_ini;
    private javax.swing.JScrollPane PnlGestion;
    private javax.swing.JTable TblFechas;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
