/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package umsa.capricornio.gui.transacciones.Adquisiciones.tramites;

import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.text.DateFormat;
import java.util.Date;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import umsa.capricornio.gui.ConnectADQUI.AdquiWSServiceLocator;
import umsa.capricornio.gui.ConnectADQUI.AdquiWSSoapBindingStub;
import umsa.capricornio.gui.ConnectADQUI.AdquiWS_PortType;
import umsa.capricornio.gui.menu.FrmMenu;
import umsa.capricornio.gui.transacciones.reporte.GetResAdj;

/**
 *
 * @author alex
 */
public class FrmtareasAdicionales extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmReporteUnidad
     */
    FrmMenu menu;
    int cc=1,tamanio=100;
    int almacenados=0;
    int cod_user, cod_rol,estado,btr;
    int gestion;
    private Runtime r;
    GetResAdj genera_res_15 = new GetResAdj();
    public JTextField jt;
    public JCheckBox jb;
    public JLabel jl;
    public String mes;
    public FrmtareasAdicionales(FrmMenu menu,int cod_user, int cod_rol,int gestion,String mes) {
        this.menu=menu;
        //this.btr=bt;
        this.cod_user=cod_user;
        this.cod_rol=cod_rol;
        this.gestion=gestion;
        this.mes=mes;
        //jPanel1.setSize(73,612);
        initComponents();
        //this.verificar_lleno();
        //jComboBox1.setVisible(false);
        //this.jButton1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGrpReporte = new javax.swing.ButtonGroup();
        BtnReporte = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JCheckBox();
        BtnReporte1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        BtnReporte2 = new javax.swing.JButton();

        setTitle("MODULO DE TAREAS");

        BtnReporte.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnReporte.setForeground(new java.awt.Color(0, 0, 255));
        BtnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umsa/capricornio/gui/images/clipboard_text.png"))); // NOI18N
        BtnReporte.setText("AGRGAR");
        BtnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReporteActionPerformed(evt);
            }
        });

        BtnSalir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnSalir.setForeground(new java.awt.Color(255, 0, 0));
        BtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umsa/capricornio/gui/images/book_previous.png"))); // NOI18N
        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("NUEVA  TAREA");

        jButton1.setText("jCheckBox1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        BtnReporte1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnReporte1.setForeground(new java.awt.Color(0, 0, 255));
        BtnReporte1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umsa/capricornio/gui/images/save_16.png"))); // NOI18N
        BtnReporte1.setText("GUARDAR");
        BtnReporte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReporte1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        BtnReporte2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnReporte2.setForeground(new java.awt.Color(255, 0, 0));
        BtnReporte2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umsa/capricornio/gui/images/clipboard_text.png"))); // NOI18N
        BtnReporte2.setText("ELIMINAR");
        BtnReporte2.setToolTipText("");
        BtnReporte2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReporte2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(BtnReporte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnReporte2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnReporte1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSalir)
                    .addComponent(BtnReporte)
                    .addComponent(BtnReporte1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnReporte2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verificar_lleno()
    {
        try{
            System.out.println("si aparece cuando cambia el combo box");
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            String x=jComboBox1.getSelectedItem().toString();
            //System.out.println(x);
            Map[] datos =puerto.mostrartareas(this.cod_user,x,gestion);
            //Map[] datos=null;
            if(datos!=null)
            {
                almacenados=datos.length;
                jTextField1.setText(datos[0].get("TAREA").toString());
                jButton1.setName(datos[0].get("ID").toString());
                for(int i=1;i<datos.length;i++)
                {
                    
                    jt=new JTextField();
                    jt.setText("");
                    jt.setVisible(true);
                    jl=new JLabel();
                    jl.setText("nueva tarea");
                    jl.setVisible(true);
                    jb=new JCheckBox();
                    jb.setVisible(true);
                    jb.setIcon(jButton1.getIcon());
                    int a=0,b=0,c,d;
                    cc++;
                    if(cc<4)
                    {
                        a=jLabel1.getX();
                        //b=jLabel1.getY()+30;
                        b=jTextField1.getY()+30;
                        c=jLabel1.getWidth();
                        d=jLabel1.getHeight();
                        System.out.println("al:"+a+" bl: "+b+" cl: "+c+" dl: "+d);
                        jl.setBounds(a, b, c, d);
                        jPanel1.add(this.jl);

                        a=jTextField1.getX();
                        b=jTextField1.getY()+30;
                        c=jTextField1.getWidth();
                        d=jTextField1.getHeight();
                        System.out.println("a:"+a+" b: "+b+" c: "+c+" d: "+d);
                        jt.setBounds(a,b,c,d);
                        jt.setName("texto"+cc);
                        jt.setText(datos[i].get("TAREA").toString());
                        System.out.println(tamanio+","+jPanel1.getSize().width+"asdojasdoijasdio");
                        jPanel1.setSize(jPanel1.getSize().height,tamanio);
                        jPanel1.setPreferredSize(jPanel1.getSize());
                        jPanel1.add(this.jt);



                        a=jButton1.getX();
                        //b=jButton1.getY()+30;
                        c=jButton1.getWidth();
                        d=jButton1.getHeight();
                        System.out.println("ab:"+a+" bb: "+b+" cb: "+c+" db: "+d);
                        jb.setName(datos[i].get("ID").toString());
                        jb.setBounds(a, b, c, d);
                        jPanel1.add(this.jb);
                    }
                    else
                    {
                        a=jLabel1.getX();
                        //b=jLabel1.getY()+30;
                        b=jTextField1.getY()+30;
                        c=jLabel1.getWidth();
                        d=jLabel1.getHeight();
                        jl.setBounds(a, b, c, d);
                        jPanel1.add(this.jl);

                        a=jTextField1.getX();
                        b=jTextField1.getY()+30;
                        c=jTextField1.getWidth();
                        d=jTextField1.getHeight();
                        System.out.println("a:"+a+" b: "+b+" c: "+c+" d: "+d);
                        jt.setBounds(a,b,c,d);
                        jt.setText(datos[i].get("TAREA").toString());
                        tamanio=tamanio+30;
                        System.out.println(tamanio+","+jPanel1.getSize().width);
                        jPanel1.setSize(jPanel1.getSize().height,tamanio);
                        jPanel1.setPreferredSize(jPanel1.getSize());
                        jPanel1.add(this.jt);
                        a=jButton1.getX();
                        //b=jButton1.getY()+30;
                        c=jButton1.getWidth();
                        d=jButton1.getHeight();
                        jb.setName(datos[i].get("ID").toString());
                        jb.setBounds(a, b, c, d);
                        jPanel1.add(this.jb);
                    }
                    jTextField1=jt;
                }
            }
            else
            {
                System.out.println("sin datos!!!!!!!!!!!!!!!");
            }
        }
        catch(Exception e)
        {
            System.out.println("esto es un error de generacion");
        }
        
    }
    private void elimina_componentes()
    {
        //jPanel1.removeAll();
        //jPanel1.re
        //System.out.println("esta removiendo todo");
        //initComponents();
        for(int i=3;i<jPanel1.getComponentCount();i++)
            jPanel1.remove(jPanel1.getComponent(i));
    }
    private void BtnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReporteActionPerformed
        jt=new JTextField();
        jt.setText("");
        jt.setVisible(true);
        jl=new JLabel();
        jl.setText("nueva tarea");
        jl.setVisible(true);
        jb=new JCheckBox();
        jb.setVisible(true);
        jb.setIcon(jButton1.getIcon());
        int a=0,b=0,c,d;
        cc++;
        if(cc<4)
        {
            a=jLabel1.getX();
            //b=jLabel1.getY()+30;
            b=jTextField1.getY()+30;
            c=jLabel1.getWidth();
            d=jLabel1.getHeight();
            System.out.println("al:"+a+" bl: "+b+" cl: "+c+" dl: "+d);
            jl.setBounds(a, b, c, d);
            jPanel1.add(this.jl);
            
            a=jTextField1.getX();
            b=jTextField1.getY()+30;
            c=jTextField1.getWidth();
            d=jTextField1.getHeight();
            System.out.println("a:"+a+" b: "+b+" c: "+c+" d: "+d);
            jt.setBounds(a,b,c,d);
            jt.setName("texto"+cc);
            System.out.println(tamanio+","+jPanel1.getSize().width+"asdojasdoijasdio");
            jPanel1.setSize(jPanel1.getSize().height,tamanio);
            jPanel1.setPreferredSize(jPanel1.getSize());
            jPanel1.add(this.jt);
            
            
            
            a=jButton1.getX();
            //b=jButton1.getY()+30;
            c=jButton1.getWidth();
            d=jButton1.getHeight();
            System.out.println("ab:"+a+" bb: "+b+" cb: "+c+" db: "+d);
            jb.setBounds(a, b, c, d);
            jPanel1.add(this.jb);
        }
        else
        {
            a=jLabel1.getX();
            //b=jLabel1.getY()+30;
            b=jTextField1.getY()+30;
            c=jLabel1.getWidth();
            d=jLabel1.getHeight();
            jl.setBounds(a, b, c, d);
            jPanel1.add(this.jl);
            
            a=jTextField1.getX();
            b=jTextField1.getY()+30;
            c=jTextField1.getWidth();
            d=jTextField1.getHeight();
            System.out.println("a:"+a+" b: "+b+" c: "+c+" d: "+d);
            jt.setBounds(a,b,c,d);
            tamanio=tamanio+30;
            System.out.println(tamanio+","+jPanel1.getSize().width);
            jPanel1.setSize(jPanel1.getSize().height,tamanio);
            jPanel1.setPreferredSize(jPanel1.getSize());
            jPanel1.add(this.jt);
            
            
            
            a=jButton1.getX();
            //b=jButton1.getY()+30;
            c=jButton1.getWidth();
            d=jButton1.getHeight();
            jb.setBounds(a, b, c, d);
            jPanel1.add(this.jb);
        }
        jTextField1=jt;
    }//GEN-LAST:event_BtnReporteActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        CerrarFrame();
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void BtnReporte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReporte1ActionPerformed
        // TODO add your handling code here:
        guardando();
        CerrarFrame();
    }//GEN-LAST:event_BtnReporte1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        //elimina_componentes();
        verificar_lleno();
        jComboBox1.setVisible(false);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void BtnReporte2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReporte2ActionPerformed
        // TODO add your handling code here:boolean df=jTextField1.getFocusTraversalKeysEnabled();
        int x=jPanel1.getComponentCount();
        JTextField[] jt=new JTextField[x];
        JCheckBox[] jc=new JCheckBox[x];
        System.out.println("esta es la cantidad del panel "+x);
        int t=1,i=0;
        /*System.out.println("aqui se muestra "+jPanel1.getComponent(1));
        jt[0]=(JTextField)jPanel1.getComponent(1);
        System.out.println(jt[0].getText());*/
        while(t<x)
        {
            
            System.out.println(t);
            jt[i]=(JTextField)jPanel1.getComponent(t);
            t=t+1;
            jc[i]=(JCheckBox)jPanel1.getComponent(t);
            System.out.println("aqui se muestra "+jPanel1.getComponent(t));
            System.out.println("esto es lo que hay que ver "+jt[i].getText());
            if(jc[i].getSelectedObjects()!=null)
            {
                try
                {
                    AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
                    AdquiWS_PortType puerto = servicio.getAdquiWS();
                    String xx=jc[i].getName();
                    Map[] datos =puerto.eliminatarea(Integer.parseInt(xx));
                    
                }
                catch(Exception e)
                {

                }
            }
                
            t=t+2;
            i++;
        }
        CerrarFrame();
        //this.verificar_lleno();
        
    }//GEN-LAST:event_BtnReporte2ActionPerformed
    private void guardando()
    {
        int x=jPanel1.getComponentCount();
        JTextField[] jt=new JTextField[x];
        System.out.println("esta es la cantidad del panel "+x);
        int t=0,i=0;
        /*System.out.println("aqui se muestra "+jPanel1.getComponent(1));
        jt[0]=(JTextField)jPanel1.getComponent(1);
        System.out.println(jt[0].getText());*/
        while(t<x)
        {
            t=t+1;
            System.out.println(t);
            jt[i]=(JTextField)jPanel1.getComponent(t);
            System.out.println("aqui se muestra "+jPanel1.getComponent(t));
            System.out.println("esto es lo que hay que ver "+jt[i].getText());
            if(i>=almacenados)
            {
                try
                {
                    AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
                    AdquiWS_PortType puerto = servicio.getAdquiWS();
                    String xx=jComboBox1.getSelectedItem().toString();            
                    Map[] datos =puerto.insertartareas(this.cod_user,jComboBox1.getSelectedItem().toString(),jt[i].getText(),gestion);
                    
                }
                catch(Exception e)
                {

                }
            }
                
            t=t+2;
            i++;
        }
    }
    void CerrarFrame(){
        menu.CerrarFrameInterno(this);
        System.gc();
        r = Runtime.getRuntime();
        long mem1 = r.freeMemory();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtnGrpReporte;
    private javax.swing.JButton BtnReporte;
    private javax.swing.JButton BtnReporte1;
    private javax.swing.JButton BtnReporte2;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JCheckBox jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
