/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package umsa.capricornio.gui.transacciones.Adquisiciones.tramites;

import java.net.URL;
import java.util.HashMap;
import java.util.Map;
import umsa.capricornio.gui.ConnectADQUI.AdquiWSServiceLocator;
import umsa.capricornio.gui.ConnectADQUI.AdquiWS_PortType;


import java.sql.Connection;
import java.sql.DriverManager;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRExporter;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.export.JRPdfExporter;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author UMSA-JES
 */
public class JD_Reporte extends javax.swing.JDialog {

    URL urlMaestro;
    /**
     * Creates new form JD_Reporte
     */
    public JD_Reporte(){
        
    }
    public JD_Reporte(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jButton1.setText("Generar Reporte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jButton1)
                .addContainerGap(201, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jButton1)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        try {
//            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
//            AdquiWS_PortType puerto = servicio.getAdquiWS();
//            Map[] datos=puerto.getRepoAdquiOrden();
//            if (datos!=null){                 
//                Map map = new HashMap();
//                System.out.println(" "+datos[0].get("COD_TRANSACCION").toString());
//                System.out.println(" "+datos[0].get("HOJA_RUTA").toString());
//                System.out.println(" "+datos[0].get("DE").toString());
//                System.out.println(" "+datos[0].get("DETALLE").toString());
//                System.out.println(" "+datos[0].get("COD_TRANS_DETALLE").toString());
//                System.out.println(" "+datos[0].get("CANTIDAD_PEDIDO").toString());
//                System.out.println(" "+datos[0].get("PRECIO_UNIT").toString());
//                System.out.println(" "+datos[0].get("ARTICULO").toString());
//                System.out.println(" "+datos[0].get("DETALLE_SOLICITUD").toString());
//                System.out.println(" "+datos[0].get("MONTO_PPTO").toString());
//                System.out.println(" "+datos[0].get("CBTE").toString());
//                System.out.println(" "+datos[0].get("ORDEN_COMPRA").toString());
//                System.out.println(" "+datos[0].get("NOMBRE_COMERCIAL").toString());
//                System.out.println(" "+datos[0].get("OBS").toString());
////                for (int f=0;f<datos.length;f++){
////                    
////                }
//            }
//        } catch (Exception e) {
//            
//        }
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            
            //Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/pruebareportes", "usuario", "password");
            Connection conexion = DriverManager.getConnection("jdbc:oracle:thin:@200.7.160.25:1521:ADQUI", "ADQUISICIONES", "4dqu1_c3n72al");
//            JD_Reporte1 t1 = new JD_Reporte1();
//            URL url = t1.getClass().getResource("/umsa/capricornio/gui/reports/ReporteAdqui1.jasper");
            JD_Reporte t1 = new JD_Reporte();
            urlMaestro = t1.getClass().getResource("/umsa/capricornio/gui/reports/ReporteAdqui1.jasper");
            JasperReport reporte = (JasperReport) JRLoader.loadObject(urlMaestro); 
            JasperPrint jasperPrint = JasperFillManager.fillReport(reporte, null, conexion);

//            JRExporter exporter = new JRPdfExporter("ReporteAdqui1.jasper");
//
//            exporter.setParameter(JRExporterParameter.JASPER_PRINT, jasperPrint);
//            exporter.setParameter(JRExporterParameter.OUTPUT_FILE, new java.io.File("reportePDF.pdf"));
//            exporter.exportReport();
            
            
//            JD_Reporte1 t1 = new JD_Reporte1(); 
//            urlMaestro = t1.getClass().getResource("/umsa/capricornio/gui/reports/SolicitudCompra.jasper");
//            
//            JasperReport masterReport = null;
//            try { masterReport = (JasperReport) JRLoader.loadObject(urlMaestro);} 
//            catch (JRException e) 
//                { System.out.println("Error cargando el reporte maestro: " + e.getMessage());
//                  System.exit(3);
//                }
//            
//            JasperPrint masterPrint = null;
//            try { masterPrint = JasperFillManager.fillReport(masterReport, null,null);}
//            catch (JRException e) {}
        
            JasperViewer.viewReport(jasperPrint, false);  
            
        } catch (Exception e) {
            System.out.println("Error Gravichimo: "+e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JD_Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JD_Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JD_Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JD_Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JD_Reporte dialog = new JD_Reporte(new javax.swing.JFrame(), false);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
