/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package umsa.capricornio.gui.transacciones.Adquisiciones.tramites;

import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.util.Map;
import javax.swing.JCheckBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static umsa.capricornio.gui.menu.FrmMenu.cod_usuario;
import javax.swing.JTextField;
import umsa.capricornio.gui.ConnectADQUI.AdquiWSServiceLocator;
import umsa.capricornio.gui.ConnectADQUI.AdquiWS_PortType;
import umsa.capricornio.gui.transacciones.Adquisiciones.tramites.*;
import umsa.capricornio.gui.transacciones.reporte.GetResAdj;
import umsa.capricornio.utilitarios.herramientas.NumerosTextuales;

/**
 *
 * @author Henrry
 */
public class JD_reporte_desierta extends javax.swing.JDialog {

    /**
     * Creates new form JDResAdj2
     */
    //String res_adm,adc,fecha_comision,inf_div_adqui,cod_proveedor,detalle,proveedor,num_resol,det_conc_prop,modo_eval,destino,cargo,actividad,prop_proveedor;
    String detalle,cod_proveedor;
    int sw=0,cod_trans_nro,cod_w,cod_transaccion,sw1=0;
    GetResAdj genera_res_adj = new GetResAdj();
    private String cuce;
    JLabel j1;
    JCheckBox jc;
    JTextField jt1,jt2,jt3,jt4,jt5;
    String s1, tprov="", tbche="";
    int tadju,gestion;
    String[] vt1;
    String[] vt2;
    String []codigos=new String[100];
    
    
    public JD_reporte_desierta(java.awt.Frame parent, boolean modal,int cod_w,int cod_trans_nro,String detalle,int cod_transaccion,int gestion) {
        super(parent, modal);
        initComponents();
        this.cod_w=cod_w;
        this.cod_trans_nro=cod_trans_nro;
        this.detalle=detalle;
        this.cod_transaccion=cod_transaccion;
        this.gestion=gestion;
        System.out.println("codigotrnas"+cod_transaccion);
        LlenaBien();
        //creatabla();
        //ejBien();
        //this.Concursantes();
        //this.bloqueaBien();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JB_Salir = new javax.swing.JButton();
        JB_Generar = new javax.swing.JButton();
        JB_Imprimir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        JB_Actualizar = new javax.swing.JButton();
        JB_Guardar = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        JTF_CARGO1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        JTF_CARGO2 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        JTF_CARGO3 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        JTF_CARGO4 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        JTF_CARGO5 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        JTF_CARGO6 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        JTF_CARGO7 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(209, 224, 240));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("GENERACION DE RESOLUCION DESIERTA");

        JB_Salir.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        JB_Salir.setForeground(new java.awt.Color(255, 0, 0));
        JB_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umsa/capricornio/gui/images/book_previous.png"))); // NOI18N
        JB_Salir.setText("SALIR");
        JB_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_SalirActionPerformed(evt);
            }
        });

        JB_Generar.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        JB_Generar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umsa/capricornio/gui/images/arrow_redo.png"))); // NOI18N
        JB_Generar.setText("GENERAR");
        JB_Generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_GenerarActionPerformed(evt);
            }
        });

        JB_Imprimir.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        JB_Imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umsa/capricornio/gui/images/printer.png"))); // NOI18N
        JB_Imprimir.setText("IMPRIMIR");
        JB_Imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ImprimirActionPerformed(evt);
            }
        });

        JB_Actualizar.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        JB_Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umsa/capricornio/gui/images/action_refresh_blue.gif"))); // NOI18N
        JB_Actualizar.setText("Actualizar");
        JB_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ActualizarActionPerformed(evt);
            }
        });

        JB_Guardar.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        JB_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umsa/capricornio/gui/images/disk.png"))); // NOI18N
        JB_Guardar.setText("Guardar");
        JB_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_GuardarActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel29.setText("RES. INICIO");

        JTF_CARGO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_CARGO1ActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel30.setText("FECHA DE APERTURA");

        JTF_CARGO2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_CARGO2ActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel31.setText("INFORME TECNICO");

        JTF_CARGO3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_CARGO3ActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel32.setText("INFORME DE ADQUISICIONES");

        JTF_CARGO4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_CARGO4ActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel33.setText("MODALIDAD");

        JTF_CARGO5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_CARGO5ActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel34.setText("DESTINO");

        JTF_CARGO6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_CARGO6ActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel35.setText("NRO DE CONVOCATORIA");

        JTF_CARGO7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_CARGO7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(JB_Actualizar)
                        .addGap(18, 18, 18)
                        .addComponent(JB_Guardar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(JB_Generar)
                        .addGap(18, 18, 18)
                        .addComponent(JB_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JB_Imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JTF_CARGO6, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel33)
                                        .addGap(149, 149, 149))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTF_CARGO5, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(JTF_CARGO1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JTF_CARGO2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JTF_CARGO3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JTF_CARGO4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JTF_CARGO7, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel1)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_CARGO1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_CARGO2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_CARGO3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_CARGO4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_CARGO5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(JTF_CARGO6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(JTF_CARGO7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_Actualizar)
                    .addComponent(JB_Guardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_Imprimir)
                    .addComponent(JB_Salir)
                    .addComponent(JB_Generar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTF_CARGO7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_CARGO7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_CARGO7ActionPerformed

    private void JTF_CARGO6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_CARGO6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_CARGO6ActionPerformed

    private void JTF_CARGO5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_CARGO5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_CARGO5ActionPerformed

    private void JTF_CARGO4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_CARGO4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_CARGO4ActionPerformed

    private void JTF_CARGO3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_CARGO3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_CARGO3ActionPerformed

    private void JTF_CARGO2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_CARGO2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_CARGO2ActionPerformed

    private void JTF_CARGO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_CARGO1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_CARGO1ActionPerformed

    private void JB_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_GuardarActionPerformed
        // TODO add your handling code here:
        /*if(this.cod_w==6)
        this.updateAdjServ(this.JTF_ADC.getText(), this.JTF_Res_Admi.getText(), this.JTF_FechaCC.getText(), this.JTF_INFDIVADQUI.getText(), this.JTF_DET_CONC_PROP.getText(), this.JTF_MEVAL.getText(), this.JTF_DESTINO.getText(), this.JTF_CARGO.getText(), this.JTF_ACTIVIDAD.getText());
        if(this.cod_w==7)
        this.updateAdjBien(this.JTF_Res_Admi.getText(), this.JTF_FechaCC.getText(), this.JTF_INFDIVADQUI.getText(), this.JTF_DET_CONC_PROP.getText(), this.JTF_MEVAL.getText(), this.JTF_DESTINO.getText(), this.JTF_CARGO.getText(), this.JTF_ACTIVIDAD.getText());
        if(this.cod_w==3)
        this.updateAdjCons(this.JTF_Res_Admi.getText(), this.JTF_FechaCC.getText(), this.JTF_INFDIVADQUI.getText(), this.JTF_DET_CONC_PROP.getText(), this.JTF_MEVAL.getText(), this.JTF_DESTINO.getText(), this.JTF_CARGO.getText(), this.JTF_ACTIVIDAD.getText());*/
        //this.verifielementos();
        //System.err.println("jijiji "+tprov+"  jujujuju "+tbche);
        //verifielementos();
        this.GuardaInfComision(JTF_CARGO1.getText(),JTF_CARGO2.getText(),JTF_CARGO3.getText(),JTF_CARGO4.getText(),JTF_CARGO5.getText(),JTF_CARGO6.getText(),JTF_CARGO7.getText());
        //this.LlenaBien();
        this.setVisible(false);
    }//GEN-LAST:event_JB_GuardarActionPerformed

    private void JB_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ActualizarActionPerformed
        // TODO add your handling code here:
        //int sw=1;
        int res = javax.swing.JOptionPane.showConfirmDialog(this, "¿Desea actualizar la Resolución de Adjudicación?",
            "MENSAJE CAPRICORNIO", javax.swing.JOptionPane.YES_NO_OPTION);
        JTF_CARGO1.setEnabled(true);
        JTF_CARGO2.setEnabled(true);
        JTF_CARGO3.setEnabled(true);
        JTF_CARGO4.setEnabled(true);
        JTF_CARGO5.setEnabled(true);
        JTF_CARGO6.setEnabled(true);
        JTF_CARGO7.setEnabled(true);
        /*JTF_CARGO8.setEnabled(true);
        JTF_CARGO9.setEnabled(true);
        JTF_CARGO10.setEnabled(true);
        JTF_CARGO11.setEnabled(true);
        JTF_CARGO12.setEnabled(true);
        JTF_CARGO13.setEnabled(true);
        JTF_CARGO14.setEnabled(true);
        JTF_CARGO15.setEnabled(true);
        JTF_CARGO16.setEnabled(true);
        JTF_CARGO17.setEnabled(true);
        JTF_CARGO18.setEnabled(true);
        for(int i=7; i<=(tadju*7)+6 ;i++)
        {
            jPanel2.getComponent(i).setEnabled(true);
        }
*/
    }//GEN-LAST:event_JB_ActualizarActionPerformed

    private void JB_ImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ImprimirActionPerformed
        // TODO add your handling code here:
        try{
            System.err.println("esto si que es raro");
            /*AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            Map[] datos =puerto.getPreventivos(cod_transaccion);*/
            this.imprimeComision(JTF_CARGO1.getText(),JTF_CARGO2.getText(),JTF_CARGO3.getText(),JTF_CARGO4.getText(),JTF_CARGO5.getText(),JTF_CARGO6.getText(),JTF_CARGO7.getText());
            System.err.println("esto si que es raro2");
            //this.genera_res_adj.ReporteAdjObra(res_adm, fecha_comision, inf_div_adqui, proveedor, detalle, num_resol, det_conc_prop, modo_eval, destino, cargo, actividad,prop_proveedor,Concursantes(),CUCE(),MONTO(),adc,tprov,tbche,cod_transaccion,this.tadju);
        }
        catch(Exception e)
        {
            System.out.println("nooo maldicion "+e.getMessage());
            System.out.println("nooo maldicion "+e);
            //JOptionPane.showMessageDialog( null, e.getMessage());
        }
        //this.genera_res_adj.Reporte(res_adm, res_adm, res_adm, adc, detalle, res_adm, fecha_comision, adc, adc, res_adm, res_adm, res_adm, cod_trans_nro, cod_w);
        /*if(this.cod_w==6)
        this.genera_res_adj.ReporteAdjServ(adc, res_adm, fecha_comision, inf_div_adqui, proveedor, detalle, num_resol, det_conc_prop, modo_eval, destino, cargo, actividad,prop_proveedor,Concursantes(),CUCE(),MONTO());
        if(this.cod_w==7)
        this.genera_res_adj.ReporteAdjBien(res_adm, fecha_comision, inf_div_adqui, proveedor, detalle, num_resol, det_conc_prop, modo_eval, destino, cargo, actividad,prop_proveedor,Concursantes(),CUCE(),MONTO());
        //        this.setVisible(false);
        if(this.cod_w==3)
        this.genera_res_adj.ReporteAdjConsul(res_adm, fecha_comision, inf_div_adqui, proveedor, detalle, num_resol, det_conc_prop, modo_eval, destino, cargo, actividad,prop_proveedor,Concursantes(),CUCE(),MONTO());*/
    }//GEN-LAST:event_JB_ImprimirActionPerformed

    private void JB_GenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_GenerarActionPerformed
        // TODO add your handling code here:
        //verifielementos();
        System.out.println("entra");
        System.out.println("--***>> el cod_w es: "+cod_w);
        //if(this.cod_w==6){
            this.GeneraInf_comision(JTF_CARGO1.getText(),JTF_CARGO2.getText(),JTF_CARGO3.getText(),JTF_CARGO4.getText(),JTF_CARGO5.getText(),JTF_CARGO6.getText(),JTF_CARGO7.getText());

            /*}
        if(this.cod_w==7||this.cod_w==1){
            this.GeneraResAdjBien();
        }
        if(this.cod_w==3){
            this.GeneraResAdjConsu();
        }*/
    }//GEN-LAST:event_JB_GenerarActionPerformed

    private void JB_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_SalirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_JB_SalirActionPerformed

    private void LlenaTabla(String t1,String t2)
    {
        vt1=t1.split(",");
        for(int i=0;i<=vt1.length-1;i++)
        {
            System.out.println("esto: "+vt1[i]);
        }
        vt2=t2.split(",");
        for(int i=0;i<=vt2.length-1;i++)
        {
            System.out.println("esto2: "+vt2[i]);
        }
    }
    
    public void GeneraInf_comision(String res_ini,String fec_apert,String inf_tec,String inf_adq,String modalidad,String destino,String convocatoria)
    {
        try{
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            System.out.println("gestion "+gestion);
            System.out.println("cod_tra "+cod_transaccion);
            System.out.println("codTN "+cod_trans_nro);
            System.out.println("detalle "+detalle);
            System.out.println("destino "+destino);
            /*System.out.println("cargo "+cargo);
            System.out.println("modalidad "+modalidad);
            System.out.println("notas "+notas);
            System.out.println("nota_juridica "+nota_juridica);
            System.out.println("citacion "+citacion);
            System.out.println("fec_cit "+fec_cit);
            System.out.println("fecha "+fecha);
            System.out.println("hora "+hora);
            System.out.println("nro_informe "+nro_informe);
            System.out.println("fecha_inf "+fecha_inf);
            System.out.println("presidente "+presidente);
            System.out.println("vocal1 "+vocal1);
            System.out.println("vocal2 "+vocal2);
            System.out.println("secretario "+secretario);
            System.out.println("nota_uni "+nota_uni);
            System.out.println("nota_ppto "+nota_ppto);
            System.out.println("resolucion_adm "+Resolucion_admi);*/
            puerto.generaDesierta(gestion, cod_transaccion, cod_trans_nro, detalle, destino, res_ini, fec_apert, inf_tec, inf_adq, modalidad, convocatoria);
            //puerto.generainf_comicion(gestion,cod_transaccion,cod_trans_nro,detalle,destino,cargo,modalidad,notas,nota_juridica,citacion,fec_cit,fecha,hora,nro_informe,fecha_inf,presidente,vocal1,vocal2,secretario,nota_uni,nota_ppto,Resolucion_admi,cod_usuario);
            System.out.println("paso");
            /*int cc=1,hh=1,nh=0;
            String []n1;
            String []n2;
            n1=tprov.split(",");
            n2=tbche.split(",");
            while(cc<n1.length)
            {
                puerto.gentabla(n1[cc], n1[cc+1], n1[cc+2], n2[hh],cod_trans_nro,codigos[nh],n1[cc+3],n1[cc+4]);
                cc=cc+5;
                /*puerto.gentabla(n1[cc], n1[cc+1], n1[cc+2], n2[hh],cod_trans_nro,codigos[nh]);
                cc=cc+3;*/
                /*hh++;
                nh++;
            }*/
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }
    private String Concursantes(){
        String conc="";
        try {
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            
            //System.out.println("- El cod_w es: "+cod_w+" y el cod_trans_nro: "+cod_trans_nro);
            Map[] datos =puerto.getConcursantes(cod_transaccion);
            if(datos!=null){
                for (int c=0;c<datos.length;c++){
                    System.out.println("Concursantes con Datos...");
                    if(datos[c].get("NOMBRE_COMERCIAL").equals("Sin Nombre Comercial"))
                    {
                        conc = conc+", "+datos[c].get("NOMBRE").toString();
                        System.out.println("uuuuuuuuu "+conc);
                    }
                    else{
                        conc = conc+", "+datos[c].get("NOMBRE_COMERCIAL").toString();
                        //System.out.println(".. "+this.num_resol);
                    }
                }
            }
            else
                System.out.println("Vacio :(");
        } catch (Exception e) {
            System.out.println("ERROR: "+e);
        }
        return conc;
    }
    private String CUCE(){
        String conc="";
        try {
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            
            //System.out.println("- El cod_w es: "+cod_w+" y el cod_trans_nro: "+cod_trans_nro);
            Map[] datos =puerto.getCuceSicoes(cod_transaccion);
            System.out.println("el nro de trans "+cod_transaccion);
            if(datos!=null){
                for (int c=0;c<datos.length;c++){
                    //System.out.println("Concursantes con Datos...");
                    conc = datos[c].get("CUCE_SICOES").toString();
                    //System.out.println(".. "+this.num_resol);
                }
            }
            else
                System.out.println("Vacio :(");
        } catch (Exception e) {
            System.out.println("ERROR: "+e);
        }
        return conc;
    }
    private String MONTO(){
        String conc="";
        Double total=0.0;
        try {
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            
            //System.out.println("- El cod_w es: "+cod_w+" y el cod_trans_nro: "+cod_trans_nro);
            Map[] datos =puerto.getPreventivos(cod_transaccion);
            if(datos!=null){
                for (int c=0;c<datos.length;c++){
                    total=total+Double.parseDouble(datos[c].get("TOTAL").toString().trim().replace(",", "."));
                }
                conc=String.valueOf(total);
                conc=conc+" "+this.TotalTexto(conc);
            }
            else
                System.out.println("Vacio :(");
        } catch (Exception e) {
            System.out.println("ERROR: "+e);
        }
        return conc;
    }
    void imprime (){
        this.JB_Imprimir.doClick();
    }
    public String hoja_ruta()
    {
        String datos=null;
        try{
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            datos=puerto.getHojaRuta(cod_transaccion);
            //Map[] d=puerto.getInformeComision(cod_transaccion, cod_trans_nro);            
        }catch(Exception e)
        {
            
        }
        return datos;
    }
    public String nro_informe()
    {
        String datos=null;
        try{
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            Map[] d=puerto.getInformeComision(cod_transaccion, cod_trans_nro);
            datos=d[0].get("NRO").toString();
        }catch(Exception e)
        {
            
        }
        return datos;
    }
    public void imprimeComision(String res_ini,String fec_apert,String inf_tec,String inf_adq,String modalidad,String destino,String convocatoria)
    {
        System.out.println("System entra hasta aqui");
        genera_res_adj.reporteDesierta(cod_w, cod_transaccion, cod_trans_nro, res_adm(), res_ini, detalle, invitados(), fec_apert, inf_tec, inf_adq, convocatoria, modalidad);
    }
    
    public String res_adm()
    {
        String datos=null;
        try{
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            Map[] d=puerto.getDesierta(cod_transaccion, cod_trans_nro);
            datos=d[0].get("NRO").toString();
        }catch(Exception e)
        {
            
        }
        return datos;
    }
    public String invitados()
    {
        String d="";
        try{
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            Map[] datos=puerto.getProponentes(this.cod_transaccion, this.cod_trans_nro);
            if (datos!=null){
                System.out.println("Entro llena proponentes...");
                for (int c=0;c<datos.length;c++){
                    if(datos[c].get("NOMBRE_COMERCIAL").toString().equals("Sin Nombre Comercial"))
                    {
                        d=d+datos[c].get("NOMBRE").toString()+", ";
                    }
                    else
                    {
                        d=d+datos[c].get("NOMBRE_COMERCIAL").toString()+", ";
                    }
                }
            }            
        }catch(Exception e)
        {
            d=null;
        }
        return d;
    }
    
    private void updateAdjObra(String res_adm,String fecha_cc,String inf_div_adq,String det_conc_prop,String modo_eval,String destino,String cargo,String actividad,String adc){
        try{
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            System.out.println("dsfsdfsdf"+adc); 
            //LlenaBien();
            //puerto.updateResAdjServ(cod_trans_nro, cod_w, res_adm, adc, fecha_cc, inf_div_adq);
            //puerto.updateResAdjObra(this.cod_trans_nro, this.cod_w, res_adm, fecha_cc, inf_div_adq, det_conc_prop, modo_eval, destino, cargo, actividad,adc,tprov,tbche,cod_usuario,this.cod_w);
            int cc=1,hh=1,nh=0;
            String []n1;
            String []n2;
            n1=tprov.split(",");
            n2=tbche.split(",");
            while(cc<n1.length)
            {
                puerto.gentabla(n1[cc], n1[cc+1], n1[cc+2], n2[hh],cod_trans_nro,codigos[nh],n1[cc+3],n1[cc+4]);
                cc=cc+5;
                hh++;
                nh++;
            }
            
            System.out.println("ResAdjObra actualizado correctamente :D");
            javax.swing.JOptionPane.showMessageDialog(this,"La Resolución de Adjudicación de servicio ha sido actualizada de forma correcta","SYSTEM CAPRICORN",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            System.out.println("ResAdjServ actualizado erroneamente :D");
        }
    }
    
    
    public void GuardaInfComision(String res_ini,String fec_apert,String inf_tec,String inf_adq,String modalidad,String destino,String convocatoria)
    {
        try{
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            /*System.out.println("gestion "+gestion);
            System.out.println("cod_tra "+cod_transaccion);
            System.out.println("codTN "+cod_trans_nro);
            System.out.println("detalle "+detalle);
            System.out.println("destino "+destino);
            System.out.println("cargo "+cargo);
            System.out.println("modalidad "+modalidad);
            System.out.println("notas "+notas);
            System.out.println("nota_juridica "+nota_juridica);
            System.out.println("citacion "+citacion);
            System.out.println("fec_cit "+fec_cit);
            System.out.println("fecha "+fecha);
            System.out.println("hora "+hora);
            System.out.println("nro_informe "+nro_informe);
            System.out.println("fecha_inf "+fecha_inf);
            System.out.println("presidente "+presidente);
            System.out.println("vocal1 "+vocal1);
            System.out.println("vocal2 "+vocal2);
            System.out.println("secretario "+secretario);
            System.out.println("nota_uni "+nota_uni);
            System.out.println("nota_ppto "+nota_ppto);
            System.out.println("resolucion_adm "+Resolucion_admi);*/
            puerto.updateDesierta(cod_transaccion, cod_trans_nro, destino, res_ini, fec_apert, inf_tec, inf_adq, modalidad, convocatoria);
            //puerto.updateInformeComision(cod_transaccion,cod_trans_nro,destino,cargo,modalidad,notas,nota_juridica,citacion,fec_cit,fecha,hora,nro_informe,fecha_inf,presidente,vocal1,vocal2,secretario,nota_uni,nota_ppto,Resolucion_admi);
            /*int cc=1,hh=1,nh=0;
            String []n1;
            String []n2;
            n1=tprov.split(",");
            n2=tbche.split(",");
            while(cc<n1.length)
            {
                puerto.gentabla(n1[cc], n1[cc+1], n1[cc+2], n2[hh],cod_trans_nro,codigos[nh],n1[cc+3],n1[cc+4]);
                cc=cc+5;
                /*puerto.gentabla(n1[cc], n1[cc+1], n1[cc+2], n2[hh],cod_trans_nro,codigos[nh]);
                cc=cc+3;*/
                /*hh++;
                nh++;
            }*/
            System.out.println("paso");
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }
    /**
     * @param args the command line arguments
     */
    private void bloqueaTodo(){
        JTF_CARGO1.setEnabled(false);
        JTF_CARGO2.setEnabled(false);
        JTF_CARGO3.setEnabled(false);
        JTF_CARGO4.setEnabled(false);
        JTF_CARGO5.setEnabled(false);
        JTF_CARGO6.setEnabled(false);
        JTF_CARGO7.setEnabled(false);
        /*JTF_CARGO8.setEnabled(false);
        JTF_CARGO9.setEnabled(false);
        JTF_CARGO10.setEnabled(false);
        JTF_CARGO11.setEnabled(false);
        JTF_CARGO12.setEnabled(false);
        JTF_CARGO13.setEnabled(false);
        JTF_CARGO14.setEnabled(false);
        JTF_CARGO15.setEnabled(false);
        JTF_CARGO16.setEnabled(false);
        JTF_CARGO17.setEnabled(false);
        JTF_CARGO18.setEnabled(false);*/
    }
    private void LlenaBien(){
        try {
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            
            System.out.println("- El cod_w es: "+cod_transaccion+" y el cod_trans_nro: "+cod_trans_nro);
            Map[] datos =puerto.getDesierta(cod_transaccion,cod_trans_nro);
            if(datos!=null){
                sw1=1;
                System.out.println("si hay datos wuju");
                //System.out.println("esto si muestra "+datos[0].get("PRESIDENTE"));
                System.out.println("Con datos :D");
                JTF_CARGO1.setText(datos[0].get("RES_ADM").toString());
                JTF_CARGO2.setText(datos[0].get("FEC_APERT_SOBRE").toString());
                JTF_CARGO3.setText(datos[0].get("NOTA_UNIDAD").toString());
                JTF_CARGO4.setText(datos[0].get("NOTAS_ADQ").toString());
                JTF_CARGO5.setText(datos[0].get("MODO_EVAL").toString());
                JTF_CARGO6.setText(datos[0].get("DESTINO").toString());
                JTF_CARGO7.setText(datos[0].get("CONVOCATORIA").toString());
                /*JTF_CARGO8.setText(datos[0].get("NRO_CITA").toString());
                JTF_CARGO9.setText(datos[0].get("FECHA_NOTA").toString());
                JTF_CARGO10.setText(datos[0].get("FEC_APERT_SOBRE").toString());
                JTF_CARGO11.setText(datos[0].get("HORA_APERT_S").toString());
                JTF_CARGO12.setText(datos[0].get("NRO_INFORME").toString());
                JTF_CARGO13.setText(datos[0].get("FECHA_INF").toString());
                JTF_CARGO14.setText(datos[0].get("NOTA_UNIDAD").toString());
                JTF_CARGO15.setText(datos[0].get("NOTA_PPTO").toString());
                JTF_CARGO16.setText(datos[0].get("RES_ADM").toString());
                JTF_CARGO17.setText(datos[0].get("DESTINO").toString());
                JTF_CARGO18.setText(datos[0].get("CARGO").toString());*/
               
                System.out.println("kkkk "+tprov+" sdfsdfsd "+tbche);
                this.bloqueaTodo();
            }
            else
                System.out.println("si es aqui");
                System.out.println("Vacio :(");
        } catch (Exception e) {
            System.out.println("ERROR: "+e);
        }
    }
    private void Genera(String res_adm, String fecha_comision, String inf_div_adqui, String det_conc_prop,String modo_eval,String destino,String cargo,String actividad,String adc)
    {
        try {
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            
            //puerto.genResAdjServ2(this.cod_trans_nro,this.cod_w, this.detalle,res_adm, adc, fecha_comision, inf_div_adqui);
            puerto.genResAdjObra(this.cod_trans_nro, 2,this.detalle, res_adm, fecha_comision, inf_div_adqui, det_conc_prop, modo_eval, destino,cargo, actividad,tprov,tbche,adc,gestion,cod_usuario);
            /*int cc=1,hh=1,nh=0;
            String []n1;
            String []n2;
            n1=tprov.split(",");
            n2=tbche.split(",");
            while(cc<n1.length)
            {
                puerto.gentabla(n1[cc], n1[cc+1], n1[cc+2], n2[hh],cod_trans_nro,codigos[nh],n1[cc+3],n1[cc+4]);
                cc=cc+5;
                /*puerto.gentabla(n1[cc], n1[cc+1], n1[cc+2], n2[hh],cod_trans_nro,codigos[nh]);
                cc=cc+3;*/
                /*hh++;
                nh++;
            }*/
            //puerto.genprop()
            javax.swing.JOptionPane.showMessageDialog(this,"La Resolución de Adjudicación de Obra ha sido generada de forma correcta","SYSTEM CAPRICORN",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
//            this.setVisible(false);
            this.LlenaBien();
            System.out.println("Se genero la R.A.O con exito :D");
            
        } catch (Exception e) {
            System.out.println("Error al generar R.A.O :(");
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDResAdjObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDResAdjObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDResAdjObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDResAdjObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDResAdjObra dialog = new JDResAdjObra(new javax.swing.JFrame(), false,6,2,"xxx","qqq",0,2015);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    String TotalTexto(String total){
        double m=Double.parseDouble(total);                          
        
        long valor =(long)m;
        double var= m-valor;
        
        DecimalFormat formato_decimal = new DecimalFormat("0.00");        
        String decimal =formato_decimal.format(var);
      
        String montoLetra=NumerosTextuales.NumTextuales(valor);
        
        if ((m>=1000 && m<2000) || (m>=1000000 && m<2000000)){ montoLetra="UN "+montoLetra;}        
        if (var ==0.0) montoLetra=montoLetra+" 00/100";
        else montoLetra=montoLetra+" "+decimal.substring(2, 4)+"/100";
       return montoLetra;
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Actualizar;
    private javax.swing.JButton JB_Generar;
    private javax.swing.JButton JB_Guardar;
    private javax.swing.JButton JB_Imprimir;
    private javax.swing.JButton JB_Salir;
    private javax.swing.JTextField JTF_CARGO1;
    private javax.swing.JTextField JTF_CARGO2;
    private javax.swing.JTextField JTF_CARGO3;
    private javax.swing.JTextField JTF_CARGO4;
    private javax.swing.JTextField JTF_CARGO5;
    private javax.swing.JTextField JTF_CARGO6;
    private javax.swing.JTextField JTF_CARGO7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
