/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package umsa.capricornio.gui.transacciones.Adquisiciones.tramites;

import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.util.Map;
import javax.swing.JCheckBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static umsa.capricornio.gui.menu.FrmMenu.cod_usuario;
import javax.swing.JTextField;
import umsa.capricornio.gui.ConnectADQUI.AdquiWSServiceLocator;
import umsa.capricornio.gui.ConnectADQUI.AdquiWS_PortType;
import umsa.capricornio.gui.transacciones.Adquisiciones.tramites.*;
import umsa.capricornio.gui.transacciones.reporte.GetResAdj;
import umsa.capricornio.utilitarios.herramientas.NumerosTextuales;

/**
 *
 * @author Henrry
 */
public class JDInformeComision extends javax.swing.JDialog {

    /**
     * Creates new form JDResAdj2
     */
    //String res_adm,adc,fecha_comision,inf_div_adqui,cod_proveedor,detalle,proveedor,num_resol,det_conc_prop,modo_eval,destino,cargo,actividad,prop_proveedor;
    String detalle,cod_proveedor;
    int sw=0,cod_trans_nro,cod_w,cod_transaccion,sw1=0;
    GetResAdj genera_res_adj = new GetResAdj();
    private String cuce;
    JLabel j1;
    JCheckBox jc;
    JTextField jt1,jt2,jt3,jt4,jt5;
    String s1, tprov="", tbche="";
    int tadju,gestion;
    String[] vt1;
    String[] vt2;
    String []codigos=new String[100];
    
    
    public JDInformeComision(java.awt.Frame parent, boolean modal,int cod_w,int cod_trans_nro,String cod_proveedor,String detalle,int cod_transaccion,int gestion) {
        super(parent, modal);
        initComponents();
        this.cod_w=cod_w;
        this.cod_trans_nro=cod_trans_nro;
        this.cod_proveedor=cod_proveedor;
        this.detalle=detalle;
        this.cod_transaccion=cod_transaccion;
        this.gestion=gestion;
        System.out.println("codigotrnas"+cod_transaccion);
        LlenaBien();
        creatabla();
        //ejBien();
        //this.Concursantes();
        //this.bloqueaBien();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JB_Salir = new javax.swing.JButton();
        JB_Generar = new javax.swing.JButton();
        JB_Imprimir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        JB_Actualizar = new javax.swing.JButton();
        JB_Guardar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        JTF_CARGO1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        JTF_CARGO2 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        JTF_CARGO3 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        JTF_CARGO4 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        JTF_CARGO5 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        JTF_CARGO6 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        JTF_CARGO7 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        JTF_CARGO8 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        JTF_CARGO9 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        JTF_CARGO10 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        JTF_CARGO11 = new javax.swing.JTextField();
        JTF_CARGO12 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        JTF_CARGO13 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        JTF_CARGO14 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        JTF_CARGO15 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        JTF_CARGO16 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        JTF_CARGO17 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        JTF_CARGO18 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(209, 224, 240));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("GENERACIÓN DE INFORME DE LA COMISION");

        JB_Salir.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        JB_Salir.setForeground(new java.awt.Color(255, 0, 0));
        JB_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umsa/capricornio/gui/images/book_previous.png"))); // NOI18N
        JB_Salir.setText("SALIR");
        JB_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_SalirActionPerformed(evt);
            }
        });

        JB_Generar.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        JB_Generar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umsa/capricornio/gui/images/arrow_redo.png"))); // NOI18N
        JB_Generar.setText("GENERAR");
        JB_Generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_GenerarActionPerformed(evt);
            }
        });

        JB_Imprimir.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        JB_Imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umsa/capricornio/gui/images/printer.png"))); // NOI18N
        JB_Imprimir.setText("IMPRIMIR");
        JB_Imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ImprimirActionPerformed(evt);
            }
        });

        JB_Actualizar.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        JB_Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umsa/capricornio/gui/images/action_refresh_blue.gif"))); // NOI18N
        JB_Actualizar.setText("Actualizar");
        JB_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ActualizarActionPerformed(evt);
            }
        });

        JB_Guardar.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        JB_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umsa/capricornio/gui/images/disk.png"))); // NOI18N
        JB_Guardar.setText("Guardar");
        JB_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_GuardarActionPerformed(evt);
            }
        });

        jLabel11.setText("DATOS DE LA TABLA DE EVALUACION");

        jLabel12.setText("EMPRESA");

        jLabel13.setText("CUMPLE");

        jLabel14.setText("MONTO PROPUESTO");

        jLabel15.setText("PLAZO DE EJECUCION");

        jLabel16.setText("OBSERVACIONES");

        jLabel26.setText("PTG E.\nECO...");

        jLabel27.setText("PTG E. \nTEC...");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(349, 349, 349))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel12)
                .addGap(214, 214, 214)
                .addComponent(jLabel13)
                .addGap(65, 65, 65)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel15)
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel16))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addComponent(jLabel27)
                .addGap(14, 14, 14)
                .addComponent(jLabel26)
                .addGap(23, 23, 23))
        );

        jScrollPane1.setViewportView(jPanel2);

        jLabel29.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel29.setText("PRESIDENTE:");

        JTF_CARGO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_CARGO1ActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel30.setText("PRIMER VOCAL:");

        JTF_CARGO2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_CARGO2ActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel31.setText("SEGUNDO VOCAL:");

        JTF_CARGO3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_CARGO3ActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel32.setText("SECRETARIO");

        JTF_CARGO4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_CARGO4ActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel33.setText("MODALIDAD");

        JTF_CARGO5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_CARGO5ActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel34.setText("NOTAS");

        JTF_CARGO6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_CARGO6ActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel35.setText("NOTA ASESOR JURIDICO");

        JTF_CARGO7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_CARGO7ActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel36.setText("CITACION MIEMBROS DE COMISION");

        JTF_CARGO8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_CARGO8ActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel37.setText("FECHA DE CITACION");

        JTF_CARGO9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_CARGO9ActionPerformed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel38.setText("FECHA");

        JTF_CARGO10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_CARGO10ActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel39.setText("HORA");

        JTF_CARGO11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_CARGO11ActionPerformed(evt);
            }
        });

        JTF_CARGO12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_CARGO12ActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel40.setText("NRO INFORME");

        JTF_CARGO13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_CARGO13ActionPerformed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel41.setText("FECHA INFORME");

        JTF_CARGO14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_CARGO14ActionPerformed(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel42.setText("NOTA DE UNIDAD");

        JTF_CARGO15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_CARGO15ActionPerformed(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel43.setText("NOTA DE PPTO");

        JTF_CARGO16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_CARGO16ActionPerformed(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel44.setText("RESOLUCION ADMINISTRATIVA");

        jLabel45.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel45.setText("DESTINO");

        JTF_CARGO17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_CARGO17ActionPerformed(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel46.setText("CARGO");

        JTF_CARGO18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_CARGO18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(JB_Generar)
                        .addGap(35, 35, 35)
                        .addComponent(JB_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(JB_Imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JB_Actualizar)
                                .addGap(109, 109, 109)
                                .addComponent(JB_Guardar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JTF_CARGO6, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel33))
                                .addGap(159, 159, 159)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTF_CARGO5, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(JTF_CARGO1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JTF_CARGO2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JTF_CARGO3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JTF_CARGO4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JTF_CARGO7, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JTF_CARGO8, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JTF_CARGO9, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JTF_CARGO10, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JTF_CARGO11, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel40)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JTF_CARGO12, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel41)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JTF_CARGO13, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel42)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JTF_CARGO14, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel43)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JTF_CARGO15, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel44)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JTF_CARGO16, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel45)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JTF_CARGO17, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel46)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JTF_CARGO18, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(JTF_CARGO1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(JTF_CARGO2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(JTF_CARGO3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_CARGO4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(JTF_CARGO5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(JTF_CARGO6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(JTF_CARGO7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(JTF_CARGO8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(JTF_CARGO9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38)
                    .addComponent(JTF_CARGO10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39)
                    .addComponent(JTF_CARGO11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addComponent(JTF_CARGO12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41)
                    .addComponent(JTF_CARGO13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42)
                    .addComponent(JTF_CARGO14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel43)
                    .addComponent(JTF_CARGO15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel44)
                    .addComponent(JTF_CARGO16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel45)
                    .addComponent(JTF_CARGO17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel46)
                    .addComponent(JTF_CARGO18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_Actualizar)
                    .addComponent(JB_Guardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_Generar)
                    .addComponent(JB_Salir)
                    .addComponent(JB_Imprimir))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void verifielementos()
    {
        int c=0,c1=0,c2=0,c3=0,c4=0,c5=0;
        JTextField jtv[]=new JTextField[30];
        JCheckBox jc[]=new JCheckBox[30];
        tprov="";
        tbche="";
        //System.out.println("total adju"+tadju*5);
        for(int i=7; i<=(tadju*7)+6 ;i++)
        {
            //System.out.println(" ");
            ///System.out.println(jPanel2.getComponent(i).getName());
            if(jPanel2.getComponent(i).getName().toString().equals("texto1"+c))
            {
                jtv[c]=(JTextField) jPanel2.getComponent(i);
                //System.out.println(jtv[c].getText().toString());
                tprov=tprov+","+jtv[c].getText();
                c++;
            }
            if(jPanel2.getComponent(i).getName().toString().equals("texto2"+c2))
            {
                jtv[c2]=(JTextField) jPanel2.getComponent(i);
                //System.out.println(jtv[c].getText().toString());
                tprov=tprov+","+jtv[c2].getText();
                c2++;
            }
            if(jPanel2.getComponent(i).getName().toString().equals("texto3"+c3))
            {
                jtv[c3]=(JTextField) jPanel2.getComponent(i);
                jtv[c3].setText(jtv[c3].getText().toLowerCase());
                System.out.println("noooooooo"+jtv[c3].getText().toString());
                tprov=tprov+","+jtv[c3].getText();
                c3++;
            }
            if(jPanel2.getComponent(i).getName().toString().equals("texto4"+c4))
            {
                jtv[c4]=(JTextField) jPanel2.getComponent(i);
                //System.out.println(jtv[c].getText().toString());
                tprov=tprov+","+jtv[c4].getText();
                c4++;
            }
            if(jPanel2.getComponent(i).getName().toString().equals("texto5"+c5))
            {
                jtv[c5]=(JTextField) jPanel2.getComponent(i);
                //System.out.println(jtv[c].getText().toString());
                tprov=tprov+","+jtv[c5].getText();
                c5++;
            }
            if(jPanel2.getComponent(i).getName().toString().equals("check1"+c1))
            {
                jc[c1]=(JCheckBox) jPanel2.getComponent(i);
                //System.out.println(jc[c1].getSelectedObjects());
                //System.out.println("c1="+c1);
                if(jc[c1].getSelectedObjects()!=null)
                   tbche=tbche+",cumple";
                else
                   tbche=tbche+",no cumple";
                c1++;
            }
            System.err.println("u"+c+"u"+c1+"u"+c2+"u"+c3+"u"+c4+"u"+c5);
            System.err.println("dsf"+jPanel2.getComponent(i).getName().toString());
        }
        //System.out.println("tprov: "+tprov+", tbche"+tbche);
    }
    private void LlenaTabla(String t1,String t2)
    {
        vt1=t1.split(",");
        for(int i=0;i<=vt1.length-1;i++)
        {
            System.out.println("esto: "+vt1[i]);
        }
        vt2=t2.split(",");
        for(int i=0;i<=vt2.length-1;i++)
        {
            System.out.println("esto2: "+vt2[i]);
        }
    }
    
    private void creatabla()
    {
        String conc="";
        //codigos[]=new String[10];
        System.out.println("entra acreartbla");
        int k=30,kk=10,kkk=572,p=1,p1=1;
        jLabel26.setBounds(840,10,60,20);
        jPanel2.add(jLabel26);
        jLabel27.setBounds(910,10,60,20);
        jPanel2.add(jLabel27);
        try {
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            
            //System.out.println("- El cod_w es: "+cod_w+" y el cod_trans_nro: "+cod_trans_nro);
            Map[] datos =puerto.getConcursantes(cod_trans_nro);
            if(datos!=null){
                tadju=datos.length;
                System.out.println("el total es: "+tadju);
                kk=kk+(datos.length-1)*50;
                kkk=kkk+(datos.length-1)*50;
                for (int c=0;c<datos.length;c++){
                    System.out.println("esto si esta aqui y sale bien");
                    System.out.println("Concursantes con Datos...");
                    if(datos[c].get("NOMBRE_COMERCIAL").equals("Sin Nombre Comercial"))
                    {
                        System.out.println("esto si esta aqui y sale bien1");
                        codigos[c]=datos[c].get("COD_PROVEEDOR").toString();
                        System.out.println("jjjjj "+codigos[c]);
                        j1=new JLabel(datos[c].get("NOMBRE").toString());
                        j1.setBounds(5, k, 300, 30);
                        j1.setText(datos[c].get("NOMBRE").toString());
                        j1.setName("label1"+c);
                        jc=new JCheckBox("si cumple");
                        jc.setBounds(300, k, 100, 30);
                        //jc.setText(datos[c].get("NOMBRE").toString());
                        jc.setVisible(true);
                        jc.setEnabled(true);
                        jc.setName("check1"+c);
                        jt1=new JTextField();
                        jt1.setBounds(410, k, 100, 30);
                        jt1.setName("texto1"+c);
                        jt2=new JTextField();
                        jt2.setBounds(520, k, 150, 30);
                        jt2.setName("texto2"+c);
                        jt3=new JTextField();
                        jt3.setBounds(680, k, 150, 30);
                        jt3.setName("texto3"+c);
                        jt4=new JTextField();
                        jt4.setBounds(840, k, 60, 30);
                        jt4.setName("texto4"+c);
                        jt5=new JTextField();
                        jt5.setBounds(910, k, 60, 30);
                        jt5.setName("texto5"+c);
                        jPanel2.add(j1);
                        jPanel2.add(jc);
                        jPanel2.add(jt1);
                        jPanel2.add(jt2);
                        jPanel2.add(jt3);
                        jPanel2.add(jt4);
                        jPanel2.add(jt5);
                        jPanel2.setSize(970, kk);
                        jPanel2.setPreferredSize(jPanel2.getSize());
                        jPanel1.setSize(997, kkk);
                       // System.out.println("WIDTH "+jPanel2.getSize());
                        jPanel1.setPreferredSize(jPanel1.getSize());
                        k=k+30;
                        conc = conc+", "+datos[c].get("NOMBRE").toString();
                        System.out.println("uuuuuuuuu "+conc+" esto es el sw"+sw1);
                        if(sw1==1)
                        {
                            System.out.println((datos[c].get("MONTO").toString()));
                            System.out.println((datos[c].get("PLAZO").toString()));
                            System.out.println((datos[c].get("OBSERVACION").toString()));
                            jt1.setText((datos[c].get("MONTO").toString()));
                            jt2.setText((datos[c].get("PLAZO").toString()));
                            jt3.setText((datos[c].get("OBSERVACION").toString()));
                            jt4.setText(datos[c].get("PTG_ECONOMICO").toString());
                            jt5.setText(datos[c].get("PTG_TECNICO").toString());
                            p=p+5;
                            
                            jt1.setEnabled(false);
                            jt2.setEnabled(false);
                            jt3.setEnabled(false);
                            jt4.setEnabled(false);
                            jt5.setEnabled(false);
                            if((datos[c].get("CUMPLE").toString()).equals("cumple"))
                                jc.setSelected(true);
                            jc.setEnabled(false);
                        }
                    }
                    else
                    {
                        System.out.println("esto si esta aqui y sale bien2");
                        codigos[c]=datos[c].get("COD_PROVEEDOR").toString();
                        System.out.println("jjjjj "+codigos[c]);
                        j1=new JLabel(datos[c].get("NOMBRE_COMERCIAL").toString());
                        j1.setBounds(5, k, 300, 30);
                        j1.setVisible(true);
                        j1.setEnabled(true);
                        j1.setName("label1"+c);
                        jc=new JCheckBox("si cumple");
                        jc.setBounds(300, k, 100, 30);
                        jc.setName("check1"+c);
                        //jc.setText(datos[c].get("NOMBRE").toString());
                        jc.setVisible(true);
                        jc.setEnabled(true);
                        jt1=new JTextField();
                        jt1.setBounds(410, k, 100, 30);
                        jt1.setName("texto1"+c);
                        jt2=new JTextField();
                        jt2.setBounds(520, k, 150, 30);
                        jt2.setName("texto2"+c);
                        jt3=new JTextField();
                        jt3.setBounds(680, k, 150, 30);
                        jt3.setName("texto3"+c);
                        jt4=new JTextField();
                        jt4.setBounds(840, k, 60, 30);
                        jt4.setName("texto4"+c);
                        jt5=new JTextField();
                        jt5.setBounds(910, k, 60, 30);
                        jt5.setName("texto5"+c);
                        jPanel2.add(j1);
                        jPanel2.add(jc);
                        jPanel2.add(jt1);
                        jPanel2.add(jt2);
                        jPanel2.add(jt3);
                        jPanel2.add(jt4);
                        jPanel2.add(jt5);
                        jPanel2.setSize(970, kk);
                        System.out.println("WIDTH1 "+jPanel1.getSize());
                        System.out.println("WIDTH2 "+jPanel2.getSize());
                        jPanel2.setPreferredSize(jPanel2.getSize());
                        jPanel1.setSize(997, kkk);
                        System.out.println("WIDTH "+jPanel2.getSize());
                        jPanel1.setPreferredSize(jPanel1.getSize());
                        k=k+30;
                        conc = conc+", "+datos[c].get("NOMBRE_COMERCIAL").toString();
                        System.out.println("aaaaaaa "+conc);
                        if(sw1==1)
                        {
                            jt1.setText((datos[c].get("MONTO").toString()));
                            jt2.setText((datos[c].get("PLAZO").toString()));
                            jt3.setText((datos[c].get("OBSERVACION").toString()));
                            jt4.setText(datos[c].get("PTG_ECONOMICO").toString());
                            jt5.setText(datos[c].get("PTG_TECNICO").toString());
                            p=p+5;
                            
                            jt1.setEnabled(false);
                            jt2.setEnabled(false);
                            jt3.setEnabled(false);
                            jt4.setEnabled(false);
                            jt5.setEnabled(false);
                            if((datos[c].get("CUMPLE").toString()).equals("cumple"))
                                jc.setSelected(true);
                            jc.setEnabled(false);
                        }
                    }
                    System.out.println("adsfsdf "+ c);
                }
            }
            else
                System.out.println("Vacio :(");
        } catch (Exception e) {
            System.out.println("ERROR: "+e);
        }
    }
    
    private void JB_GenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_GenerarActionPerformed
        // TODO add your handling code here:        
        verifielementos();
        System.out.println("entra");
        System.out.println("--***>> el cod_w es: "+cod_w);
        //if(this.cod_w==6){
        this.GeneraInf_comision(JTF_CARGO1.getText(),JTF_CARGO2.getText(),JTF_CARGO3.getText(),JTF_CARGO4.getText(),JTF_CARGO5.getText(),JTF_CARGO6.getText(),JTF_CARGO7.getText(),JTF_CARGO8.getText(),JTF_CARGO9.getText(),JTF_CARGO10.getText(),JTF_CARGO11.getText(),JTF_CARGO12.getText(),JTF_CARGO13.getText(),JTF_CARGO14.getText(),JTF_CARGO15.getText(),JTF_CARGO16.getText(),JTF_CARGO17.getText(),JTF_CARGO18.getText());
        
        
        /*}
        if(this.cod_w==7||this.cod_w==1){
            this.GeneraResAdjBien();
        }
        if(this.cod_w==3){
            this.GeneraResAdjConsu();
        }*/
    }//GEN-LAST:event_JB_GenerarActionPerformed

    public void GeneraInf_comision(String presidente,String vocal1,String vocal2,String secretario,String modalidad,String notas,String nota_juridica,String citacion,String fec_cit,String fecha,String hora,String nro_informe,String fecha_inf,String nota_uni,String nota_ppto,String Resolucion_admi,String destino,String cargo)
    {
        try{
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            System.out.println("gestion "+gestion);
            System.out.println("cod_tra "+cod_transaccion);
            System.out.println("codTN "+cod_trans_nro);
            System.out.println("detalle "+detalle);
            System.out.println("destino "+destino);
            System.out.println("cargo "+cargo);
            System.out.println("modalidad "+modalidad);
            System.out.println("notas "+notas);
            System.out.println("nota_juridica "+nota_juridica);
            System.out.println("citacion "+citacion);
            System.out.println("fec_cit "+fec_cit);
            System.out.println("fecha "+fecha);
            System.out.println("hora "+hora);
            System.out.println("nro_informe "+nro_informe);
            System.out.println("fecha_inf "+fecha_inf);
            System.out.println("presidente "+presidente);
            System.out.println("vocal1 "+vocal1);
            System.out.println("vocal2 "+vocal2);
            System.out.println("secretario "+secretario);
            System.out.println("nota_uni "+nota_uni);
            System.out.println("nota_ppto "+nota_ppto);
            System.out.println("resolucion_adm "+Resolucion_admi);
            puerto.generainf_comicion(gestion,cod_transaccion,cod_trans_nro,detalle,destino,cargo,modalidad,notas,nota_juridica,citacion,fec_cit,fecha,hora,nro_informe,fecha_inf,presidente,vocal1,vocal2,secretario,nota_uni,nota_ppto,Resolucion_admi,cod_usuario);
            System.out.println("paso");
            int cc=1,hh=1,nh=0;
            String []n1;
            String []n2;
            n1=tprov.split(",");
            n2=tbche.split(",");
            while(cc<n1.length)
            {
                puerto.gentabla(n1[cc], n1[cc+1], n1[cc+2], n2[hh],cod_trans_nro,codigos[nh],n1[cc+3],n1[cc+4]);
                cc=cc+5;
                /*puerto.gentabla(n1[cc], n1[cc+1], n1[cc+2], n2[hh],cod_trans_nro,codigos[nh]);
                cc=cc+3;*/
                hh++;
                nh++;
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }
    private void JB_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_SalirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_JB_SalirActionPerformed

    private String Concursantes(){
        String conc="";
        try {
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            
            //System.out.println("- El cod_w es: "+cod_w+" y el cod_trans_nro: "+cod_trans_nro);
            Map[] datos =puerto.getConcursantes(cod_transaccion);
            if(datos!=null){
                for (int c=0;c<datos.length;c++){
                    System.out.println("Concursantes con Datos...");
                    if(datos[c].get("NOMBRE_COMERCIAL").equals("Sin Nombre Comercial"))
                    {
                        conc = conc+", "+datos[c].get("NOMBRE").toString();
                        System.out.println("uuuuuuuuu "+conc);
                    }
                    else{
                        conc = conc+", "+datos[c].get("NOMBRE_COMERCIAL").toString();
                        //System.out.println(".. "+this.num_resol);
                    }
                }
            }
            else
                System.out.println("Vacio :(");
        } catch (Exception e) {
            System.out.println("ERROR: "+e);
        }
        return conc;
    }
    private String CUCE(){
        String conc="";
        try {
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            
            //System.out.println("- El cod_w es: "+cod_w+" y el cod_trans_nro: "+cod_trans_nro);
            Map[] datos =puerto.getCuceSicoes(cod_transaccion);
            System.out.println("el nro de trans "+cod_transaccion);
            if(datos!=null){
                for (int c=0;c<datos.length;c++){
                    //System.out.println("Concursantes con Datos...");
                    conc = datos[c].get("CUCE_SICOES").toString();
                    //System.out.println(".. "+this.num_resol);
                }
            }
            else
                System.out.println("Vacio :(");
        } catch (Exception e) {
            System.out.println("ERROR: "+e);
        }
        return conc;
    }
    private String MONTO(){
        String conc="";
        Double total=0.0;
        try {
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            
            //System.out.println("- El cod_w es: "+cod_w+" y el cod_trans_nro: "+cod_trans_nro);
            Map[] datos =puerto.getPreventivos(cod_transaccion);
            if(datos!=null){
                for (int c=0;c<datos.length;c++){
                    total=total+Double.parseDouble(datos[c].get("TOTAL").toString().trim().replace(",", "."));
                }
                conc=String.valueOf(total);
                conc=conc+" "+this.TotalTexto(conc);
            }
            else
                System.out.println("Vacio :(");
        } catch (Exception e) {
            System.out.println("ERROR: "+e);
        }
        return conc;
    }
    void imprime (){
        this.JB_Imprimir.doClick();
    }
    public String hoja_ruta()
    {
        String datos=null;
        try{
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            datos=puerto.getHojaRuta(cod_transaccion);
            //Map[] d=puerto.getInformeComision(cod_transaccion, cod_trans_nro);            
        }catch(Exception e)
        {
            
        }
        return datos;
    }
    public String nro_informe()
    {
        String datos=null;
        try{
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            Map[] d=puerto.getInformeComision(cod_transaccion, cod_trans_nro);
            datos=d[0].get("NRO").toString();
        }catch(Exception e)
        {
            
        }
        return datos;
    }
    public void imprimeComision(String presidente,String vocal1,String vocal2,String secretario,String modalidad,String notas,String nota_juridica,String citacion,String fec_cit,String fecha,String hora,String nro_informe,String fecha_inf,String nota_uni,String nota_ppto,String Resolucion_admi,String destino,String cargo)
    {
        System.out.println("System entra hasta aqui "+cod_proveedor);
        genera_res_adj.imprimeinf_comicion(cod_w,gestion,cod_transaccion,cod_trans_nro,detalle,destino,cargo,modalidad,notas,nota_juridica,citacion,fec_cit,fecha,hora,nro_informe,fecha_inf,presidente,vocal1,vocal2,secretario,nota_uni,nota_ppto,Resolucion_admi,MONTO(),hoja_ruta(),nro_informe(),cod_proveedor);
    }
    private void JB_ImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ImprimirActionPerformed
        // TODO add your handling code here:
        try{
            System.err.println("esto si que es raro");
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            Map[] datos =puerto.getPreventivos(cod_transaccion);
            this.imprimeComision(JTF_CARGO1.getText(),JTF_CARGO2.getText(),JTF_CARGO3.getText(),JTF_CARGO4.getText(),JTF_CARGO5.getText(),JTF_CARGO6.getText(),JTF_CARGO7.getText(),JTF_CARGO8.getText(),JTF_CARGO9.getText(),JTF_CARGO10.getText(),JTF_CARGO11.getText(),JTF_CARGO12.getText(),JTF_CARGO13.getText(),JTF_CARGO14.getText(),JTF_CARGO15.getText(),JTF_CARGO16.getText(),JTF_CARGO17.getText(),JTF_CARGO18.getText());
            System.err.println("esto si que es raro2");
        //this.genera_res_adj.ReporteAdjObra(res_adm, fecha_comision, inf_div_adqui, proveedor, detalle, num_resol, det_conc_prop, modo_eval, destino, cargo, actividad,prop_proveedor,Concursantes(),CUCE(),MONTO(),adc,tprov,tbche,cod_transaccion,this.tadju);
        }
        catch(Exception e)
        {
            System.out.println("nooo maldicion "+e.getMessage());
            System.out.println("nooo maldicion "+e);
            //JOptionPane.showMessageDialog( null, e.getMessage());
        }
        //this.genera_res_adj.Reporte(res_adm, res_adm, res_adm, adc, detalle, res_adm, fecha_comision, adc, adc, res_adm, res_adm, res_adm, cod_trans_nro, cod_w);
        /*if(this.cod_w==6)
            this.genera_res_adj.ReporteAdjServ(adc, res_adm, fecha_comision, inf_div_adqui, proveedor, detalle, num_resol, det_conc_prop, modo_eval, destino, cargo, actividad,prop_proveedor,Concursantes(),CUCE(),MONTO());
        if(this.cod_w==7)
            this.genera_res_adj.ReporteAdjBien(res_adm, fecha_comision, inf_div_adqui, proveedor, detalle, num_resol, det_conc_prop, modo_eval, destino, cargo, actividad,prop_proveedor,Concursantes(),CUCE(),MONTO());
//        this.setVisible(false);
        if(this.cod_w==3)
            this.genera_res_adj.ReporteAdjConsul(res_adm, fecha_comision, inf_div_adqui, proveedor, detalle, num_resol, det_conc_prop, modo_eval, destino, cargo, actividad,prop_proveedor,Concursantes(),CUCE(),MONTO());*/
    }//GEN-LAST:event_JB_ImprimirActionPerformed

    
    private void JB_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ActualizarActionPerformed
        // TODO add your handling code here:
        //int sw=1;
        int res = javax.swing.JOptionPane.showConfirmDialog(this, "¿Desea actualizar la Resolución de Adjudicación?",
                "MENSAJE CAPRICORNIO", javax.swing.JOptionPane.YES_NO_OPTION);
        JTF_CARGO1.setEnabled(true);
        JTF_CARGO2.setEnabled(true);
        JTF_CARGO3.setEnabled(true);
        JTF_CARGO4.setEnabled(true);
        JTF_CARGO5.setEnabled(true);
        JTF_CARGO6.setEnabled(true);
        JTF_CARGO7.setEnabled(true);
        JTF_CARGO8.setEnabled(true);
        JTF_CARGO9.setEnabled(true);
        JTF_CARGO10.setEnabled(true);
        JTF_CARGO11.setEnabled(true);
        JTF_CARGO12.setEnabled(true);
        JTF_CARGO13.setEnabled(true);
        JTF_CARGO14.setEnabled(true);
        JTF_CARGO15.setEnabled(true);
        JTF_CARGO16.setEnabled(true);
        JTF_CARGO17.setEnabled(true);
        JTF_CARGO18.setEnabled(true);
        for(int i=7; i<=(tadju*7)+6 ;i++)
        {
            jPanel2.getComponent(i).setEnabled(true);
        }
        
    }//GEN-LAST:event_JB_ActualizarActionPerformed

    private void updateAdjObra(String res_adm,String fecha_cc,String inf_div_adq,String det_conc_prop,String modo_eval,String destino,String cargo,String actividad,String adc){
        try{
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            System.out.println("dsfsdfsdf"+adc); 
            //LlenaBien();
            //puerto.updateResAdjServ(cod_trans_nro, cod_w, res_adm, adc, fecha_cc, inf_div_adq);
            puerto.updateResAdjObra(this.cod_trans_nro, this.cod_w, res_adm, fecha_cc, inf_div_adq, det_conc_prop, modo_eval, destino, cargo, actividad,adc,tprov,tbche,cod_usuario);
            int cc=1,hh=1,nh=0;
            String []n1;
            String []n2;
            n1=tprov.split(",");
            n2=tbche.split(",");
            while(cc<n1.length)
            {
                puerto.gentabla(n1[cc], n1[cc+1], n1[cc+2], n2[hh],cod_trans_nro,codigos[nh],n1[cc+3],n1[cc+4]);
                cc=cc+5;
                hh++;
                nh++;
            }
            
            System.out.println("ResAdjObra actualizado correctamente :D");
            javax.swing.JOptionPane.showMessageDialog(this,"La Resolución de Adjudicación de servicio ha sido actualizada de forma correcta","SYSTEM CAPRICORN",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            System.out.println("ResAdjServ actualizado erroneamente :D");
        }
    }
    
    private void JB_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_GuardarActionPerformed
        // TODO add your handling code here:
        /*if(this.cod_w==6)
            this.updateAdjServ(this.JTF_ADC.getText(), this.JTF_Res_Admi.getText(), this.JTF_FechaCC.getText(), this.JTF_INFDIVADQUI.getText(), this.JTF_DET_CONC_PROP.getText(), this.JTF_MEVAL.getText(), this.JTF_DESTINO.getText(), this.JTF_CARGO.getText(), this.JTF_ACTIVIDAD.getText());
        if(this.cod_w==7)
            this.updateAdjBien(this.JTF_Res_Admi.getText(), this.JTF_FechaCC.getText(), this.JTF_INFDIVADQUI.getText(), this.JTF_DET_CONC_PROP.getText(), this.JTF_MEVAL.getText(), this.JTF_DESTINO.getText(), this.JTF_CARGO.getText(), this.JTF_ACTIVIDAD.getText());
        if(this.cod_w==3)
            this.updateAdjCons(this.JTF_Res_Admi.getText(), this.JTF_FechaCC.getText(), this.JTF_INFDIVADQUI.getText(), this.JTF_DET_CONC_PROP.getText(), this.JTF_MEVAL.getText(), this.JTF_DESTINO.getText(), this.JTF_CARGO.getText(), this.JTF_ACTIVIDAD.getText());*/
        //this.verifielementos();
        //System.err.println("jijiji "+tprov+"  jujujuju "+tbche);
        verifielementos();
        this.GuardaInfComision(JTF_CARGO1.getText(),JTF_CARGO2.getText(),JTF_CARGO3.getText(),JTF_CARGO4.getText(),JTF_CARGO5.getText(),JTF_CARGO6.getText(),JTF_CARGO7.getText(),JTF_CARGO8.getText(),JTF_CARGO9.getText(),JTF_CARGO10.getText(),JTF_CARGO11.getText(),JTF_CARGO12.getText(),JTF_CARGO13.getText(),JTF_CARGO14.getText(),JTF_CARGO15.getText(),JTF_CARGO16.getText(),JTF_CARGO17.getText(),JTF_CARGO18.getText());
        //this.LlenaBien();
        this.setVisible(false);
    }//GEN-LAST:event_JB_GuardarActionPerformed

    
    public void GuardaInfComision(String presidente,String vocal1,String vocal2,String secretario,String modalidad,String notas,String nota_juridica,String citacion,String fec_cit,String fecha,String hora,String nro_informe,String fecha_inf,String nota_uni,String nota_ppto,String Resolucion_admi,String destino,String cargo)
    {
        try{
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            System.out.println("gestion "+gestion);
            System.out.println("cod_tra "+cod_transaccion);
            System.out.println("codTN "+cod_trans_nro);
            System.out.println("detalle "+detalle);
            System.out.println("destino "+destino);
            System.out.println("cargo "+cargo);
            System.out.println("modalidad "+modalidad);
            System.out.println("notas "+notas);
            System.out.println("nota_juridica "+nota_juridica);
            System.out.println("citacion "+citacion);
            System.out.println("fec_cit "+fec_cit);
            System.out.println("fecha "+fecha);
            System.out.println("hora "+hora);
            System.out.println("nro_informe "+nro_informe);
            System.out.println("fecha_inf "+fecha_inf);
            System.out.println("presidente "+presidente);
            System.out.println("vocal1 "+vocal1);
            System.out.println("vocal2 "+vocal2);
            System.out.println("secretario "+secretario);
            System.out.println("nota_uni "+nota_uni);
            System.out.println("nota_ppto "+nota_ppto);
            System.out.println("resolucion_adm "+Resolucion_admi);
            puerto.updateInformeComision(cod_transaccion,cod_trans_nro,destino,cargo,modalidad,notas,nota_juridica,citacion,fec_cit,fecha,hora,nro_informe,fecha_inf,presidente,vocal1,vocal2,secretario,nota_uni,nota_ppto,Resolucion_admi);
            int cc=1,hh=1,nh=0;
            String []n1;
            String []n2;
            n1=tprov.split(",");
            n2=tbche.split(",");
            while(cc<n1.length)
            {
                puerto.gentabla(n1[cc], n1[cc+1], n1[cc+2], n2[hh],cod_trans_nro,codigos[nh],n1[cc+3],n1[cc+4]);
                cc=cc+5;
                /*puerto.gentabla(n1[cc], n1[cc+1], n1[cc+2], n2[hh],cod_trans_nro,codigos[nh]);
                cc=cc+3;*/
                hh++;
                nh++;
            }
            System.out.println("paso");
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }
    private void JTF_CARGO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_CARGO1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_CARGO1ActionPerformed

    private void JTF_CARGO2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_CARGO2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_CARGO2ActionPerformed

    private void JTF_CARGO3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_CARGO3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_CARGO3ActionPerformed

    private void JTF_CARGO4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_CARGO4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_CARGO4ActionPerformed

    private void JTF_CARGO5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_CARGO5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_CARGO5ActionPerformed

    private void JTF_CARGO6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_CARGO6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_CARGO6ActionPerformed

    private void JTF_CARGO7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_CARGO7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_CARGO7ActionPerformed

    private void JTF_CARGO8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_CARGO8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_CARGO8ActionPerformed

    private void JTF_CARGO9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_CARGO9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_CARGO9ActionPerformed

    private void JTF_CARGO10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_CARGO10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_CARGO10ActionPerformed

    private void JTF_CARGO11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_CARGO11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_CARGO11ActionPerformed

    private void JTF_CARGO12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_CARGO12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_CARGO12ActionPerformed

    private void JTF_CARGO13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_CARGO13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_CARGO13ActionPerformed

    private void JTF_CARGO14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_CARGO14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_CARGO14ActionPerformed

    private void JTF_CARGO15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_CARGO15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_CARGO15ActionPerformed

    private void JTF_CARGO16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_CARGO16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_CARGO16ActionPerformed

    private void JTF_CARGO17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_CARGO17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_CARGO17ActionPerformed

    private void JTF_CARGO18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_CARGO18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_CARGO18ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void bloqueaTodo(){
        JTF_CARGO1.setEnabled(false);
        JTF_CARGO2.setEnabled(false);
        JTF_CARGO3.setEnabled(false);
        JTF_CARGO4.setEnabled(false);
        JTF_CARGO5.setEnabled(false);
        JTF_CARGO6.setEnabled(false);
        JTF_CARGO7.setEnabled(false);
        JTF_CARGO8.setEnabled(false);
        JTF_CARGO9.setEnabled(false);
        JTF_CARGO10.setEnabled(false);
        JTF_CARGO11.setEnabled(false);
        JTF_CARGO12.setEnabled(false);
        JTF_CARGO13.setEnabled(false);
        JTF_CARGO14.setEnabled(false);
        JTF_CARGO15.setEnabled(false);
        JTF_CARGO16.setEnabled(false);
        JTF_CARGO17.setEnabled(false);
        JTF_CARGO18.setEnabled(false);
    }
    private void LlenaServicio(){
        System.out.println("En llena servicio");
        try {
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            
            System.out.println("- El cod_w es: "+cod_w+" y el cod_trans_nro: "+cod_trans_nro);
            Map[] datos =puerto.getResAdjServ(cod_trans_nro);
            if(datos!=null){
                /*this.adc = datos[0].get("DET_ADC").toString();
                System.out.println(".. "+this.adc);
                this.res_adm = datos[0].get("DET_RES_ADM").toString();
               
                this.fecha_comision = datos[0].get("FECHA_CC").toString(); 
                this.inf_div_adqui = datos[0].get("DET_INF_DIV_ADQ").toString();
                this.proveedor = datos[0].get("PROVEEDOR").toString();
                this.num_resol = datos[0].get("NUM_RESOLUCION").toString();
                
                this.det_conc_prop = datos[0].get("DET_CONC_PROP").toString();
                this.modo_eval = datos[0].get("MODO_EVAL").toString();
                this.destino = datos[0].get("DESTINO").toString();
                this.cargo = datos[0].get("CARGO").toString();
                this.actividad = datos[0].get("ACTIVIDAD").toString();
                this.prop_proveedor =datos[0].get("ADH_NOMBRE").toString();*/
                
                
                
                
                this.bloqueaTodo();
            }
            else
                System.out.println("Vacio :(");
        } catch (Exception e) {
            System.out.println("ERROR: "+e);
        }
    }
    private void LlenaBien(){
        try {
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            
            System.out.println("- El cod_w es: "+cod_w+" y el cod_trans_nro: "+cod_trans_nro);
            Map[] datos =puerto.getInformeComision(cod_transaccion,cod_trans_nro);
            if(datos!=null){
                sw1=1;
                System.out.println("si hay datos wuju");
                //System.out.println("esto si muestra "+datos[0].get("PRESIDENTE"));
                System.out.println("Con datos :D");
                JTF_CARGO1.setText(datos[0].get("PRESIDENTE").toString());
                JTF_CARGO2.setText(datos[0].get("VOCAL1").toString());
                JTF_CARGO3.setText(datos[0].get("VOCAL2").toString());
                JTF_CARGO4.setText(datos[0].get("SECRETARIO").toString());
                JTF_CARGO5.setText(datos[0].get("MODO_EVAL").toString());
                JTF_CARGO6.setText(datos[0].get("NOTAS_ADQ").toString());
                JTF_CARGO7.setText(datos[0].get("NOTA_JUR").toString());
                JTF_CARGO8.setText(datos[0].get("NRO_CITA").toString());
                JTF_CARGO9.setText(datos[0].get("FECHA_NOTA").toString());
                JTF_CARGO10.setText(datos[0].get("FEC_APERT_SOBRE").toString());
                JTF_CARGO11.setText(datos[0].get("HORA_APERT_S").toString());
                JTF_CARGO12.setText(datos[0].get("NRO_INFORME").toString());
                JTF_CARGO13.setText(datos[0].get("FECHA_INF").toString());
                JTF_CARGO14.setText(datos[0].get("NOTA_UNIDAD").toString());
                JTF_CARGO15.setText(datos[0].get("NOTA_PPTO").toString());
                JTF_CARGO16.setText(datos[0].get("RES_ADM").toString());
                JTF_CARGO17.setText(datos[0].get("DESTINO").toString());
                JTF_CARGO18.setText(datos[0].get("CARGO").toString());
               
                System.out.println("kkkk "+tprov+" sdfsdfsd "+tbche);
                this.bloqueaTodo();
            }
            else
                System.out.println("Vacio :(");
        } catch (Exception e) {
            System.out.println("ERROR: "+e);
        }
    }
    
    private void LlenaCons(){
        try {
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            
            System.out.println("- El cod_w es: "+cod_w+" y el cod_trans_nro: "+cod_trans_nro);
            Map[] datos =puerto.getResAdjConsul(cod_trans_nro);
            if(datos!=null){
                /*System.out.println("Con datos :D");
                this.res_adm = datos[0].get("DET_RES_ADM").toString();
               
                this.fecha_comision = datos[0].get("FECHA_CC").toString(); 
                this.inf_div_adqui = datos[0].get("DET_INF_DIV_ADQ").toString();
                this.proveedor = datos[0].get("PROVEEDOR").toString();
                this.num_resol = datos[0].get("NUM_RESOLUCION").toString();
                
                this.det_conc_prop = datos[0].get("DET_CONC_PROP").toString();
                this.modo_eval = datos[0].get("MODO_EVAL").toString();
                this.destino = datos[0].get("DESTINO").toString();
                this.cargo = datos[0].get("CARGO").toString();
                this.actividad = datos[0].get("ACTIVIDAD").toString();
                this.prop_proveedor =datos[0].get("ADH_NOMBRE").toString();
                */
                
                
                this.bloqueaTodo();
            }
            else{
                System.out.println("Vacio :(");
                //this.JB_Actualizar.setVisible(false);
                //this.JB_Guardar.setVisible(false);
            }
        } catch (Exception e) {
            System.out.println("ERROR: "+e);
        }
    }
    private void LlenaDatos(){
        if(this.cod_w==6)
            this.LlenaServicio();
        if(this.cod_w==7)
            this.LlenaBien();
        if(this.cod_w==3)
            this.LlenaCons();
        
    }
    
    private void Genera(String res_adm, String fecha_comision, String inf_div_adqui, String det_conc_prop,String modo_eval,String destino,String cargo,String actividad,String adc)
    {
        try {
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            
            //puerto.genResAdjServ2(this.cod_trans_nro,this.cod_w, this.detalle,res_adm, adc, fecha_comision, inf_div_adqui);
            puerto.genResAdjObra(this.cod_trans_nro, 2,this.detalle, res_adm, fecha_comision, inf_div_adqui, det_conc_prop, modo_eval, destino,cargo, actividad,tprov,tbche,adc,gestion,cod_usuario);
            int cc=1,hh=1,nh=0;
            String []n1;
            String []n2;
            n1=tprov.split(",");
            n2=tbche.split(",");
            while(cc<n1.length)
            {
                puerto.gentabla(n1[cc], n1[cc+1], n1[cc+2], n2[hh],cod_trans_nro,codigos[nh],n1[cc+3],n1[cc+4]);
                cc=cc+5;
                /*puerto.gentabla(n1[cc], n1[cc+1], n1[cc+2], n2[hh],cod_trans_nro,codigos[nh]);
                cc=cc+3;*/
                hh++;
                nh++;
            }
            //puerto.genprop()
            javax.swing.JOptionPane.showMessageDialog(this,"La Resolución de Adjudicación de Obra ha sido generada de forma correcta","SYSTEM CAPRICORN",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
//            this.setVisible(false);
            this.LlenaBien();
            System.out.println("Se genero la R.A.O con exito :D");
            
        } catch (Exception e) {
            System.out.println("Error al generar R.A.O :(");
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDResAdjObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDResAdjObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDResAdjObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDResAdjObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDResAdjObra dialog = new JDResAdjObra(new javax.swing.JFrame(), false,6,2,"xxx","qqq",0,2015);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    String TotalTexto(String total){
        double m=Double.parseDouble(total);                          
        
        long valor =(long)m;
        double var= m-valor;
        
        DecimalFormat formato_decimal = new DecimalFormat("0.00");        
        String decimal =formato_decimal.format(var);
      
        String montoLetra=NumerosTextuales.NumTextuales(valor);
        
        if ((m>=1000 && m<2000) || (m>=1000000 && m<2000000)){ montoLetra="UN "+montoLetra;}        
        if (var ==0.0) montoLetra=montoLetra+" 00/100";
        else montoLetra=montoLetra+" "+decimal.substring(2, 4)+"/100";
       return montoLetra;
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Actualizar;
    private javax.swing.JButton JB_Generar;
    private javax.swing.JButton JB_Guardar;
    private javax.swing.JButton JB_Imprimir;
    private javax.swing.JButton JB_Salir;
    private javax.swing.JTextField JTF_CARGO1;
    private javax.swing.JTextField JTF_CARGO10;
    private javax.swing.JTextField JTF_CARGO11;
    private javax.swing.JTextField JTF_CARGO12;
    private javax.swing.JTextField JTF_CARGO13;
    private javax.swing.JTextField JTF_CARGO14;
    private javax.swing.JTextField JTF_CARGO15;
    private javax.swing.JTextField JTF_CARGO16;
    private javax.swing.JTextField JTF_CARGO17;
    private javax.swing.JTextField JTF_CARGO18;
    private javax.swing.JTextField JTF_CARGO2;
    private javax.swing.JTextField JTF_CARGO3;
    private javax.swing.JTextField JTF_CARGO4;
    private javax.swing.JTextField JTF_CARGO5;
    private javax.swing.JTextField JTF_CARGO6;
    private javax.swing.JTextField JTF_CARGO7;
    private javax.swing.JTextField JTF_CARGO8;
    private javax.swing.JTextField JTF_CARGO9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
