/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package umsa.capricornio.gui.transacciones.Adquisiciones.tramites;

import java.awt.Dialog;
import java.util.Map;
import javax.swing.JOptionPane;
import umsa.capricornio.gui.ConnectADQUI.AdquiWSServiceLocator;
import umsa.capricornio.gui.ConnectADQUI.AdquiWS_PortType;
import umsa.capricornio.gui.menu.FrmMenu;
import umsa.capricornio.gui.transacciones.reporte.GetResoluciones;

/**
 *
 * @author Henrry
 */
public class ResolucionInicio extends javax.swing.JFrame {

    /**
     * Creates new form ResolucionInicio
     */
    String detalle;
    FrmMenu menu;
    int cod_transaccion, cod_w, cod_res_ini=0,dias,cod_trans_nro,gestion,cod_resolucion;
    String envia,dns,dnp,destino,num_resolucion,monto_ppto;
    String detalle_uni_sol,detalle_autorizacion,jefe_adqui,detalle_recursos;
    private int cod_almacen;
    GetResoluciones genera_reportes;
  
    public ResolucionInicio(String detalle, int cod_transaccion, int cod_w, int cod_almacen, java.awt.Frame menu_ ,int cod_trans_nro,int gestion ) {
        //this.setFocusable(true);
        this.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        initComponents();
        this.gestion=gestion;
        this.detalle=detalle;
        this.cod_transaccion=cod_transaccion;
        this.cod_w=cod_w;
        this.cod_trans_nro=cod_trans_nro;
        this.menu=(FrmMenu) menu_;
        genera_reportes = new  GetResoluciones(cod_almacen);
        bloqueo();
        LlenaDatos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTFEnviado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JTFDns = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JTFPpto = new javax.swing.JTextField();
        jBGenerar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBImprimir = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        JTFDestino = new javax.swing.JTextField();
        jBGuardar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTA_DetUniSol = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTA_DetAutorizacion = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JTF_JefeAdqui = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        JTF_DetRec = new javax.swing.JTextField();

        jInternalFrame1.setBackground(new java.awt.Color(185, 203, 221));
        jInternalFrame1.setVisible(true);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("GENERAR RESOLUCION DE INICIO");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel2.setText("Enviad@ por:");

        JTFEnviado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFEnviadoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel3.setText("Detalle nota solicitante:");

        JTFDns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFDnsActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel4.setText("Detalle nota presupuesto");

        JTFPpto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFPptoActionPerformed(evt);
            }
        });

        jBGenerar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umsa/capricornio/gui/images/arrow_redo.png"))); // NOI18N
        jBGenerar.setText("Generar");
        jBGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGenerarActionPerformed(evt);
            }
        });

        jBModificar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umsa/capricornio/gui/images/action_refresh_blue.gif"))); // NOI18N
        jBModificar.setText("Actualizar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        jBImprimir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umsa/capricornio/gui/images/printer.png"))); // NOI18N
        jBImprimir.setText("Imprimir");
        jBImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBImprimirActionPerformed(evt);
            }
        });

        jBSalir.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jBSalir.setForeground(new java.awt.Color(255, 51, 51));
        jBSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umsa/capricornio/gui/images/book_previous.png"))); // NOI18N
        jBSalir.setText("SALIR");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel5.setText("Destino:");

        JTFDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFDestinoActionPerformed(evt);
            }
        });

        jBGuardar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umsa/capricornio/gui/images/disk.png"))); // NOI18N
        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umsa/capricornio/gui/images/alarm.png"))); // NOI18N
        jButton1.setText("Fechas Limite");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        JTA_DetUniSol.setColumns(20);
        JTA_DetUniSol.setRows(5);
        jScrollPane2.setViewportView(JTA_DetUniSol);

        JTA_DetAutorizacion.setColumns(20);
        JTA_DetAutorizacion.setRows(5);
        jScrollPane3.setViewportView(JTA_DetAutorizacion);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel6.setText("Detalle Unidad Solicitante:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel7.setText("Detalle Autorización:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel8.setText("Jefe Adquisiciones:");

        JTF_JefeAdqui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_JefeAdquiActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel9.setText("Detalle Recursos:");

        JTF_DetRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_DetRecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jBImprimir)
                .addGap(157, 157, 157))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JTF_DetRec, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JTF_JefeAdqui, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jBModificar)
                        .addGap(284, 284, 284)
                        .addComponent(jBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(69, 69, 69)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(JTFEnviado, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JTFDns, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JTFPpto, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JTFDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3))))
                .addGap(0, 60, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTFEnviado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTFDns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JTFPpto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(JTFDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel8))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(JTF_JefeAdqui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(JTF_DetRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 22, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jBModificar)
                    .addComponent(jBGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBImprimir)
                    .addComponent(jBSalir)
                    .addComponent(jBGenerar))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFPptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFPptoActionPerformed
        // TODO add your handling code here:
        this.JTFDestino.requestFocus();
    }//GEN-LAST:event_JTFPptoActionPerformed

    private void bloqueo(){
        if( cod_w==3){
            this.JTFDestino.setEnabled(false);
        }
    }
    private void bloqueaTodo(){
        this.JTFEnviado.setEnabled(false);
        this.JTFDns.setEnabled(false);
        this.JTFPpto.setEnabled(false);
        this.JTFDestino.setEnabled(false);
        this.jBGuardar.setEnabled(false);
        
        this.JTA_DetUniSol.setEnabled(false);
        this.JTA_DetAutorizacion.setEnabled(false);
        this.JTF_DetRec.setEnabled(false);
        this.JTF_JefeAdqui.setEnabled(false);
    }
    private void desbloqueaTodo(){
        this.JTFEnviado.setEnabled(true);
        this.JTFDns.setEnabled(true);
        this.JTFPpto.setEnabled(true);
        this.JTFDestino.setEnabled(true);
        
        this.JTA_DetUniSol.setEnabled(true);
        this.JTA_DetAutorizacion.setEnabled(true);
        this.JTF_DetRec.setEnabled(true);
        this.JTF_JefeAdqui.setEnabled(true);
    }
    private void LlenaDatos(){
        String dias1="";
        try {
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            //System.out.println("Para cod_transaccion: "+cod_transaccion);
            System.out.println("***--> el cod_transaccion es: "+cod_transaccion);
            Map[] datos =puerto.getResIni(cod_transaccion);
            if(datos!=null){
                this.jBModificar.setVisible(true);
                this.jBGuardar.setVisible(true);
                this.jButton1.setEnabled(true);
                this.jButton1.setVisible(true);
                //System.out.println("Devolvio Datos :P"+datos[0].get("DETALLE").toString());
//                System.out.println("1");
                this.envia=datos[0].get("ENVIA").toString();
                this.dns=datos[0].get("DETALLE_NOTA_SOLICITUD").toString();
                this.dnp=datos[0].get("DETALLE_NOTA_PRESUPUESTO").toString();
                this.destino=datos[0].get("DESTINO").toString();
                this.cod_resolucion = Integer.parseInt(datos[0].get("COD_RESOLUCION").toString());
                this.cod_res_ini=Integer.parseInt(datos[0].get("NRO").toString());
                this.num_resolucion=datos[0].get("NUM_RESOLUCION").toString();
                dias1=(datos[0].get("DIAS").toString());
//                this.monto_ppto=datos[0].get("MONTO_PPTO").toString();
                
                this.JTFEnviado.setText(envia);
                this.JTFDns.setText(dns);
                this.JTFPpto.setText(dnp);
                this.JTFDestino.setText(destino);
                //this.jTextField1.setText(dias1);
                
                this.detalle_autorizacion=datos[0].get("DET_AUT").toString();
                this.detalle_recursos=datos[0].get("DET_RECURSOS").toString();
                this.detalle_uni_sol=datos[0].get("DET_UNI_SOL").toString();
                this.jefe_adqui=datos[0].get("JEFE_ADQUI").toString();
                
                
                this.JTA_DetUniSol.setText(detalle_uni_sol);
                this.JTA_DetAutorizacion.setText(detalle_autorizacion);
                this.JTF_DetRec.setText(detalle_recursos);
                this.JTF_JefeAdqui.setText(jefe_adqui);
                
                bloqueaTodo();
                MsjAlertaFechas(puerto);
         
            }
            else{
                this.jBModificar.setVisible(false);
                this.jBGuardar.setVisible(false);
                this.jButton1.setVisible(false);
                System.out.println("Vacio");
            }
        } catch (Exception e) {
            System.out.println("Errorr :(");
        }
    }
    private void MsjAlertaFechas(AdquiWS_PortType puerto){
        try {
            Map[] datos = puerto.getFechasRestriccion(cod_transaccion);
            javax.swing.JOptionPane.showMessageDialog(this,"El tramite se inicio el : "+datos[0].get("FECHA_INICIO").toString()+" \ntiene hasta el "+datos[0].get("FECHA_FINAL").toString()+" para que el tramite concluya","SYSTEM CAPRICORN",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
        }
        
    }
    private void GuardaResIni(){
        this.envia=this.JTFEnviado.getText();
        this.dns=this.JTFDns.getText();
        this.dnp=this.JTFPpto.getText();
        this.destino=this.JTFDestino.getText();
        
        this.jefe_adqui=this.JTF_JefeAdqui.getText().trim();
        this.detalle_recursos=this.JTF_DetRec.getText().trim();
        this.detalle_autorizacion=this.JTA_DetAutorizacion.getText().trim();
        this.detalle_uni_sol=this.JTA_DetUniSol.getText().trim();
//        this.dias=Integer.parseInt(this.jTextField1.getText());
        try {
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            
//            System.out.println("cod_transaccion: "+cod_transaccion);
//            System.out.println("cod_w: "+cod_w);
//            System.out.println("detalle: "+detalle);
//            System.out.println("envia: "+envia);
//            System.out.println("dns: "+dns);
//            System.out.println("dnp: "+dnp);
//            System.out.println("destino: "+destino);
                        
            puerto.generaResIni(cod_transaccion, 1, detalle, envia, dns, dnp, destino, dias, gestion,jefe_adqui,detalle_recursos,detalle_uni_sol,detalle_autorizacion);
            
            javax.swing.JOptionPane.showMessageDialog(this,"La Resolución de inicio ha sido generada de forma correcta","SYSTEM CAPRICORN",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            this.LlenaDatos();
//            this.setVisible(false);
            System.out.println("Exito :D");
            
        } catch (Exception e) {
            System.out.println("Error :(");
        }
    }
    private void jBGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGenerarActionPerformed
        // TODO add your handling code here:
        System.out.println("OOOO :D :D OOOOO");
        //System.out.println(this.jTextField1.getText());
        //System.out.println(this.jTextField2.getText());
        //System.out.println(this.jTextField3.getText());
        System.out.println("El cod_res_ini es : "+this.cod_res_ini);
        if(this.cod_res_ini==0){
           GuardaResIni(); 
        }else{
            javax.swing.JOptionPane.showMessageDialog(this,"Ya se genero la resolucion de inicio","SYSTEM CAPRICORN",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
        
        ///////////////////
       
        /*
        GetResoluciones x = new  GetResoluciones();
        System.out.println("1: "+this.JTFDns.getText()+" 2: "+this.JTFPpto.getText()+" 3: "+this.JTFEnviado.getText()+" 4: "+this.detalle+" 5: "+this.cod_transaccion+" 6: "+this.cod_w);
        x.Reporte(this.cod_transaccion,this.cod_w,this.detalle,envia,dns,dnp,destino);
        this.setVisible(false);
        */
    }//GEN-LAST:event_jBGenerarActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        // TODO add your handling code here:
        //this.finalize();
        this.setVisible(false);
    }//GEN-LAST:event_jBSalirActionPerformed

    private void JTFDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFDestinoActionPerformed
        // TODO add your handling code here:
        this.jBGenerar.requestFocus();
    }//GEN-LAST:event_JTFDestinoActionPerformed

    private void ActualizaResIni(){
        try {
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            this.envia=this.JTFEnviado.getText();
            this.dns=this.JTFDns.getText();
            this.dnp=this.JTFPpto.getText();
            this.destino=this.JTFDestino.getText();
            
            this.detalle_autorizacion=this.JTA_DetAutorizacion.getText();
            this.detalle_recursos=this.JTF_DetRec.getText();
            this.detalle_uni_sol=this.JTA_DetUniSol.getText();
            this.jefe_adqui=this.JTF_JefeAdqui.getText();
//            this.dias=Integer.parseInt(this.jTextField1.getText());
            
            puerto.updateResIni(cod_resolucion, envia, dns, dnp, destino, dias,jefe_adqui,detalle_recursos,detalle_uni_sol,detalle_autorizacion);
            //puerto.generaResIni(cod_transaccion, cod_w, detalle, envia, dns, dnp, destino);
            System.out.println("Exito :D");
            javax.swing.JOptionPane.showMessageDialog(this,"La Resolución de inicio ha sido modificada exitosamente","SYSTEM CAPRICORN",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
            
        } catch (Exception e) {
            System.out.println("Error :(");
        }
    }
    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        // TODO add your handling code here:
        /*
        this.JTFEnviado.setEnabled(true);
        this.JTFDns.setEnabled(true);
        this.JTFPpto.setEnabled(true);
        this.JTFDestino.setEnabled(true);
        */
        int res = javax.swing.JOptionPane.showConfirmDialog(this, "¿Desea actualizar la Resolución de Inicio?",
                "MENSAJE CAPRICORNIO", javax.swing.JOptionPane.YES_NO_OPTION);
        if (res == javax.swing.JOptionPane.YES_OPTION) {
            desbloqueaTodo();
            bloqueo();
            this.jBGuardar.setEnabled(true);
            this.jBGenerar.setEnabled(false);
            this.jBImprimir.setEnabled(false);
            this.jBModificar.setEnabled(false);
            this.jButton1.setEnabled(false);
        }
        
        //LlenaDatos();
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jBImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBImprimirActionPerformed
        // TODO add your handling code here:
        if(this.cod_res_ini!=0){
            
            //System.out.println("1: "+this.JTFDns.getText()+" 2: "+this.JTFPpto.getText()+" 3: "+this.JTFEnviado.getText()+" 4: "+this.detalle+" 5: "+this.cod_transaccion+" 6: "+this.cod_w);
            this.genera_reportes.Reporte(this.cod_transaccion,this.cod_w,this.detalle);
            this.setVisible(false);
        }else{
            javax.swing.JOptionPane.showMessageDialog(this,"Todavia no se a generado la resolución","SYSTEM CAPRICORN",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jBImprimirActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        // TODO add your handling code here:
        ActualizaResIni();
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void JTFEnviadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFEnviadoActionPerformed
        // TODO add your handling code here:
        //System.out.println("Helllo world");
        this.JTFDns.requestFocus();
    }//GEN-LAST:event_JTFEnviadoActionPerformed

    private void JTFDnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFDnsActionPerformed
        // TODO add your handling code here:
        this.JTFPpto.requestFocus();
    }//GEN-LAST:event_JTFDnsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int sw=0,sw1=0;
        String proceso = null,fecha = null;
        try {
            AdquiWSServiceLocator servicio = new AdquiWSServiceLocator();
            AdquiWS_PortType puerto = servicio.getAdquiWS();
            Map[] datos = puerto.getCuceSicoes(cod_transaccion);
            System.err.println("uno");
            Map[] datos1 =puerto.getResIni(cod_transaccion);
            System.err.println("uno");
            if(datos1==null)
            {
                sw=1;
            }
            else{
                sw=0;
            }
            System.err.println("uno"+cod_trans_nro);
            Map[] datos2=puerto.dias_restantes(cod_trans_nro);
            System.err.println("uno");
            int dias=Integer.parseInt(datos2[0].get("DIAS_RESTANTES").toString());
            System.out.println("estos son los dias "+ dias);
            if(dias>=0)
            {
                sw1=0;
            }
            else
            {
                proceso=datos2[0].get("PROCESO").toString();
                fecha=datos2[0].get("FECHA").toString();
                sw1=1;
            }
            System.out.println("asdasd "+datos);
            if(!datos[0].get("CUCE_SICOES").toString().equals("")){
                System.out.println("--> "+datos[0].get("CUCE_SICOES").toString());
                //cuce_sicoes = datos[0].get("CUCE_SICOES").toString();
            }
            else{
                String resp=JOptionPane.showInputDialog("Ingresa el CUCE del SICOES para poner las fechas");
                if(resp==null || resp.equals(""))
                {
                    return;
                }
                else
                {
                    try {
                    puerto.addCuceSicoes("SET-addCuceSicoes", cod_transaccion, resp);
                    } catch (Exception e) {
                    }  
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "USTED DEBE GENERAR LA RESOLUCION DE INICIO PRIMERO "+e);
        }
        if(sw==0)
        {
            if(sw1==0)
            {
            JD_FECH_ANPE JDF = new JD_FECH_ANPE(this, false, this.cod_trans_nro, this.cod_transaccion);
            JDF.setVisible(true);
            }
            else
               JOptionPane.showMessageDialog(null, "DEBIDO A QUE EL PROCESO: \n"+proceso+" HA EXPIRTADO EL TIEMPO ESTABLECIDO: "+fecha+"\nDEBE PRESENTAR UNA PRORROGA PARA REANUDARLO" ); 
        }
        else
            JOptionPane.showMessageDialog(this, "USTED DEBE GENERAR LA RESOLUCION DE INICIO PRIMERO");
        //JDF.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JTF_JefeAdquiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_JefeAdquiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_JefeAdquiActionPerformed

    private void JTF_DetRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_DetRecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_DetRecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResolucionInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResolucionInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResolucionInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResolucionInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ResolucionInicio("Detalle",12,0).setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JTA_DetAutorizacion;
    private javax.swing.JTextArea JTA_DetUniSol;
    private javax.swing.JTextField JTFDestino;
    private javax.swing.JTextField JTFDns;
    private javax.swing.JTextField JTFEnviado;
    private javax.swing.JTextField JTFPpto;
    private javax.swing.JTextField JTF_DetRec;
    private javax.swing.JTextField JTF_JefeAdqui;
    private javax.swing.JButton jBGenerar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBImprimir;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
